### ISSUE TITLE
Agricraft + Fluiduct Crash

### ISSUE THREAD

**Issue by Black0305** [pyure/infitech-prototype#101]
1. Place Agricraft Tank, fill it with water and attach two Fluiducts with a servo to extract water
2. Break the second Fluiduct
3. Crash https://pastebin.com/19uEKcCB

![agricrash](https://user-images.githubusercontent.com/42079463/44989714-0b536900-af8f-11e8-9827-70c36a70846c.JPG)

**Comment by Black0305** [comment]
Should be fixed in next release.
https://github.com/CoFH/Feedback/issues/1278

**Comment by pyure** [comment]
Fix in infitech-prototype-0.20.zip (or 0.19, I forget)

**Comment by pyure** [comment]
Closed prematurely.

**Comment by pyure** [comment]
infitech-prototype-0.22.zip
