### ISSUE TITLE
Add load-in tooltip for BQ hotkey

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#103]
Giving the player a book is an alternative, but would prefer the tooltip I think.

From RedBlockFilms

**Comment by pyure** [comment]
Does anyone know how to fire a startup message to player?

**Comment by McRayJason** [comment]
https://minecraft.curseforge.com/projects/mputils
with
https://minecraft.curseforge.com/projects/mputils-tip-alert

**Comment by Agrax** [comment]
This looks noice

**Comment by pyure** [comment]
There's no 1.12.2 for mputils-tip-alert that I can find.

What about: https://github.com/pyure/infitech-prototype/issues/103

**Comment by pyure** [comment]
What about https://minecraft.curseforge.com/projects/tipline

**Comment by pyure** [comment]
No longer relevant since we're changing our approach to quests
