### ISSUE TITLE
Multiple gunpowder recipes

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#106]
Gunpowder has 3 gregtech recipes (normal, gregtech default), 2 TF recipes, and 1 natura recipe, all with different resource requirements and outputs. I assume we want to keep the gregtech recipe and remove the others

**Comment by Black0305** [comment]
Fixed.

**Comment by pyure** [comment]
Fix in infitech-prototype-0.20.zip
