### ISSUE TITLE
Metal Cutting Machine recipe broken?

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#108]
I've been trying to make the Metal Cutting Machine (factory tech), I put in the pieces manually and using JEI auto-fill neither actually crafts it. I'm using the GT iron tool rods and an Iron Wrench (with 8 durability missing)

**Comment by RedBlockFilms** [comment]
Same thing's happening with the advanced motor, I think it's something to do with the GT iron rods

**Comment by Agrax** [comment]
Oh, yeah. I remember the issue. It’s actually caused by the lack of nickel rods item, but they’re present in the recipe

**Comment by Agrax** [comment]
#109 should fix it

**Comment by pyure** [comment]
Fix in infitech-prototype-0.20.zip
