### ISSUE TITLE
Metal Caster can't turn bronze into ingots

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#123]
The foundry metal caster can't cast bronze into ingots, you need to use the metal atomizer to get bronze out of liquid form. The ingot casting table doesn't work either. The metal atomizer also needs power to operate, therefor you can't do anything with bronze in the foundry

**Comment by Agrax** [comment]
„The ingot casting table doesn’t work either”. How are you trying to use it? Have you considered using molds? The table requires molds to work ie: an ingot one

**Comment by RedBlockFilms** [comment]
I know this. I put the metal caster under a spout with an ingot mold inside. The fluid won't cast. The same thing happens when you pour it into the ingot casting table, the fluid just sits in it and never forms. I definitely have enough molten bronze, too. Also, if you check JEI, it only shows that you can use molten bronze in a metal atomizer

**Comment by Agrax** [comment]
I'll check that

**Comment by RedBlockFilms** [comment]
I think the reason why it doesn't work is because I made the liquid bronze in the alloying crucible, and that creates Liquid Bronze from foundry. If you put a bronze ingot straight in the the melting crucible it will melt into Bronze from GTCE and that can be cast

**Comment by Black0305** [comment]
I'll fix it later, should be in my Script

**Comment by Agrax** [comment]
@Black0305 in this PR #119 or another you're preparing?

**Comment by Black0305** [comment]
Another one

**Comment by RedBlockFilms** [comment]
Another related thing. Using the alloying crucible to make this bronze takes 3 copper and 1 tin for 2 bronze ingots, yet grinding into dust instead give 3 bronze

**Comment by Black0305** [comment]
Fixed.

**Comment by pyure** [comment]
Fix in infitech-prototype-0.20.zip
