### ISSUE TITLE
Molten Bronze has 4 recipes with Foundry

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#124]
There are 4 different recipes for molten bronze in the alloying crucible, each one uses different types of liquid metal. 1 for foundry+foundry, 1 for GT+foundry, 1 for foundry+GT, 1 for GT+GT. Each recipe also gives different amounts of molten bronze, from foundry. The last recipe, being the default, uses 3 GT copper and 1 GT tin, but only give 2 bronze

**Comment by Black0305** [comment]
Fixed.

**Comment by pyure** [comment]
Released in infitech-prototype-0.20.zip
