### ISSUE TITLE
broze pipes + microblock stone cover results in client crash

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#153]
Created a stone cover from forge microblocks to place on a small bronze pipe (gtce) carrying steam.  As soon as the cover moves over the pipe the client will crash.  Tried it in a test world, with and without steam, on all the sizes of bronze pipe with similar result.

Crash Log: https://pastebin.com/3eN1pWTr

**Comment by pyure** [comment]
infitech-prototype-0.23.zip

Worth noting, there's another (different) different issue with pipes and FMP: placing a cover on a GT pipe transforms the block into some non-pipe-FMP block (or something).  Tomorrow I'll try to remember to make a GT issue for that.
