### ISSUE TITLE
LV Quests - Magnetizing - Magnetic Iron Rod not detected

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#162]
Version: 0.22b

On the 2nd part of the quest, after creating a magnetic iron rod it is not detected to complete the quest.
The first part of the quest, 1 iron rod and 4 red stone detected properly.

**Comment by Agrax** [comment]
Apparently there’s a major issue with crafting tasks o.O

**Comment by pyure** [comment]
infitech-prototype-0.23.zip
