### ISSUE TITLE
Super Laggy Steam Turbine

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#169]
Using the turbo steam turbine. Over 120 fps when off
![inked2018-10-07_21 58 54_li](https://user-images.githubusercontent.com/30029228/46590885-6c81c700-ca7c-11e8-990d-8a9e0b917b47.jpg)
But the moment I give it steam or remove the power stored...
![inked2018-10-07_21 59 03_li](https://user-images.githubusercontent.com/30029228/46590898-802d2d80-ca7c-11e8-8f9b-8141c2002da3.jpg)
Fps drops to about 10-15. I tested, even when full of steam this still happens. Many of the generators do this. It's not just dependent on the generator turning off and on from not having enough fuel

**Comment by pyure** [comment]
I wasn't able to get the crippling FPS drop you did, but I did get a drastic reduction from just one machine.  I've mentioned it to the GT guys.

**Comment by pyure** [comment]
Arch made some tweaks.  I'm gonna close this cuz its either addressed to some degree or just not reproducible to some degree.

infitech-prototype-0.23.zip
