### ISSUE TITLE
Smelting armor returns nuggets

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#170]
Version: 0.22b

When smelting armor, damaged or undamaged, it returns a single nugget specific to the metal type.
Not necessarily sure if that is bad or not, just different.

**Comment by Agrax** [comment]
One thing i know it’s that it isn’t intended

**Comment by pyure** [comment]
Xavion scripted up a solution for this, should be in next version.

**Comment by Xavion3** [comment]
I don't actually touch the nugget recipes, should I make it do something with them?

**Comment by pyure** [comment]
Woops, my mistake.  Leave the nuggets for now; at least now there are alternative options.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.32.zip or prior (woops)
