### ISSUE TITLE
Steel Age - Volcanization Quest - Suggestion for reworking

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#178]
Version: 0.22b

The Volcanization quest is possibly overly complex and not geared quite for an LV quest line.  It also has a few issues that need to be resolved in the world in general.

I worked thru the requirements to make 1 small pile of polyvinyl chloride pulp.

-mixer to make salt water
-electrolyze saltwater to get chlorine and hydrogen
-distill oil to get sulfuric naptha (Unknown oil source, issue #1)
-electrolyze water to get oxygen (could skip this step and do the last chemical reaction with air for less gain)
-chemical reactor hydrogen/sulfuric naptha to get naptha
-chemical reactor naptha/steam to get steam-cracked naptha
-distill steam cracked naptha to get ethylene
-chemical reactor chlorine/ethylene to get vinyl chloride
-chemical reactor vinyl chloride with air or oxygen to get polyvinyl chloride (144mb vs 216mb)  requires a compressor if doing air.
-mold the liquid polyvinyl chloride out to an ingot
-macerate ingot into dust and craft dust into 4 small piles of polyvinyl chloride pulp.

11-12 machines depending on if you go with air vs no air.  That's not horrible, its a good exercise in machine use and setting up production lines.

My issue is that its overly complicated for an LV quest.
My suggestion is to knock it down a lot:

-make the 2000mb rubber
-use your previously made electrolyzer to make oxygen
-make an arc furnace
-use arc furnace w/oxygen to make annealed copper wire
-use your previously made assembler to make annealed copper cable (rubber/wire/chipset)

One of the 'world issues' is that there is currently NO reasonable source of oil in the world.  
-Fluid oil generation is rare/non-existant (as multiple cofh clearall experiments have shown)
-Oil sands/shale has been disabled in the pack.

Without a solution to the oil issue there can be no step 3 from the list above and the quest item cannot be made.

If someone can work out a solution that I have overlooked (I'm not infallible) please point it out, I am just making a suggestion for something more practical that can work with what we currently have in 0.22b

p.s. Its Vulcanization :) (ala vulcanized rubber)

**Comment by Agrax** [comment]
I have this thing covered. The quest was made in the time when i was 100% sure there’s a strict progression to cables:
Annealed cables with just rubber-> copper cables with the more awkward rubber-> the rest

**Comment by pyure** [comment]
infitech-prototype-0.23.zip
