### ISSUE TITLE
Quest Rotor-a-plenty got darmstadtium parts instead of tin

### ISSUE THREAD

**Issue by Sandrox1099** [pyure/infitech-prototype#190]
![tin parts](https://user-images.githubusercontent.com/24881685/47377255-0c825600-d6f5-11e8-8674-c71ea13aa4c0.PNG)

The tin bending cylinders are accepted but it looks bad.

**Comment by Agrax** [comment]
We don't really care abt bending cylinder material. You need ANY bending cylinder in order to make tin parts used in LV motors/rotors/w/e
