### ISSUE TITLE
Voids for Items/Liquids/Power

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#192]
Version 0.23b

Currently there are no ways in the pack to void items, liquids(gas) or energy.  Previously in IT2, we had things like trashcans which would handle each of those or buildcraft void pipes.
An equivalent would be greatly desired.

**Comment by pyure** [comment]
Furi4n mentioned this as a possible option, noting it here as a reminder to self:
https://minecraft.curseforge.com/projects/trashcans-reborn

**Comment by ct-klein** [comment]
Nuclearcraft has void machines for energy/items/power.  Single block device, can’t recall name atm, cannot get in game

**Comment by pyure** [comment]
I've created a task to modify the existing Universal Bin recipe so that its available (reasonably) early game.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.32.zip
