### ISSUE TITLE
Some ores don't double

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#203]
In the foundry melting crucible, banded iron ore and iron ore double but yellow & brown limonite ore don't.

**Comment by Agrax** [comment]
Uh, but do we need IMpure ores to double? Maybe not as much as 1,5x multiplier
They can be a tad bit worse than their pure counterparts

Do you find this solution satisfactory?

**Comment by pyure** [comment]
Making the limonites (which are comprised of considerable Oxygen) provide a bit less iron via foundry is more or less consistent with some other limonite-related decisions, I'm good with that.  

This is all notwithstanding that furnacing limonite produces the same metal as furnacing iron.  If that distinction is a problem,  I'd rather just reduce the amount of iron produced by furnacing limonite. (not part of this task btw)

**Comment by RedBlockFilms** [comment]
I think it was probably a bad move to make ores double in foundry seeing how it's steam level whereas GT needs at least LV to double full ores. So maybe make crushed ores/impure dusts do 1 1/3 or 1 2/3 ingots (so you don't have half nuggets) in the foundry instead?

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.32.zip
