### ISSUE TITLE
Right tool for the right job

### ISSUE THREAD

**Issue by CharlieTuna8** [pyure/infitech-prototype#209]
Maybe add a wire cutter to the list of tools needed, you need it to craft the scoop anyway.

**Comment by Agrax** [comment]
There's already a quest for wire cutters. In the LV age. To close

**Comment by pyure** [comment]
@Agrax can we streamline this somehow someway?  If we make the user craft a scoop which requires the cutters, and then ask for cutters later, they'll probably have to craft the cutters twice.

(And crafting cutters kind of sucks to begin with)

Possible ideas:
* Add the cutters as suggested by CharlieTuna8
* Remove the Scoop requirement
* Move the existing Cutters requirement

**Comment by Agrax** [comment]
No, no and no
1. 2 places where you need the same item? O.o
2. It’s needed for bees
3. Cutters are needed for wires more than for the scoop

**Comment by pyure** [comment]
@CharlieTuna8 I'm not going to veto Agrax w/o a better plan to improve the situation.  We'll keep an eye on it.

**Comment by pyure** [comment]
Came up with a better plan to improve the situation.  Its fixed in dev.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.40.zip
