### ISSUE TITLE
Suggestion: Add Controlling

### ISSUE THREAD

**Issue by davqvist** [pyure/infitech-prototype#212]
The Controlling mod would help resolving key conflicts which to me is basically necessary for any bigger modpack.

**Comment by pyure** [comment]
Looks applicable.  I'll review.

**Comment by pyure** [comment]
Fine in review.  Thanks for the suggestion @davqvist.  Will probably appear in next update.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.32.zip
