### ISSUE TITLE
Crash involving gendustry in stage 2 of loading

### ISSUE THREAD

**Issue by MaXimumLava** [pyure/infitech-prototype#218]
https://pastebin.com/YKrKPFQY

**Comment by MaXimumLava** [comment]
infitech-prototype-0.30

**Comment by pyure** [comment]
MaximumLava how did you install the pack?  Did you just download the zip and do Custom Profile -> Import, or use a launcher?

**Comment by MaXimumLava** [comment]
I tried both ways to see if it was the way that it installed and every way crashed the game. I imported the zip into the twitch launcher at first and that crashed the game. After the first crash, I tried installing it from the launcher and that crashed it as well.

**Comment by pyure** [comment]
Thanks.  I don't have a solution for you at this time (I don't get the same behaviour) but we'll keep an eye on it.

**Comment by pyure** [comment]
Closing this.  I can't seem to make it happen.  Will reopen if the issue persists with other players.
