### ISSUE TITLE
Advanced Generator and Wood pulp

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#223]
Version: 0.30

Interesting little fuel multiplier for the Advanced Generator.  1 wood gives you 1600 'carbon' units, which is what the syngas producer uses.  Forestry carpenter makes 1 wood = 4 wood pulp.  Each wood pulp is 1600 'carbon' units.  GTCE doesn't assign a carbon value to its wood pulp.
I'd either nix the carpentry recipe that makes wood pulp or better see if there is a way to set the carbon value of the wood pulp to 400, which would be in line with the 1600 for standard wood log.

**Comment by pyure** [comment]
i went with the 400 output route, thanks ct-klein.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.32.zip
