### ISSUE TITLE
Foundry machines slightly too buff

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#238]
Look into ways to nudge Foundry usefulness down 5-10%.

**Comment by RTHauke** [comment]
Not sure if you messed with this in prototype 38 or not.  Seems pretty useless in current state as it's only giving 27mb of liquid metal to each crushed ore.  Looking at JEI, any input ore of any form just gives 27mb.  Whereas an ingot requires 144mb.

**Comment by Agrax** [comment]
Umm, yeah. We know. Pyure was in too much of a rush and just cut down everything to 27 mb without looking at the recipes :D

**Comment by pyure** [comment]
Yeah, at the time, it was based on a different understanding of the new ores system.  

I've removed Crushed and Dusts from Foundry processing since there's too many variations to worry about.  * "Pure" ores will give 15 nuggets. 
* "Impure" ores will give only 12 nuggets.

This tech is more or less available before you're likely to get a Macerator.    It also lets you make some tools somewhat cheaper than before LV or MV.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.39.1 I believe.
