### ISSUE TITLE
Bibliocraft Tool Rack and GT tools

### ISSUE THREAD

**Issue by Detrav** [pyure/infitech-prototype#239]
I can not put gt tools to bibliocraft tool rack

**Comment by Agrax** [comment]
Yeah. We know. You’re playing on a server, right?

**Comment by Detrav** [comment]
Yes, I recently started playing on my own server with friends, now it is the 0.32 version in the twitch app

**Comment by Agrax** [comment]
Righto. We know the bug, but unfortunatelly it’s either on the Bibliocraft’s or GTCE’s side

**Comment by Detrav** [comment]
In the bibliocraft.cfg config, there is a section `general -> S:AdditionalTools`, 

```
general {
    # These are the names of additional tools that can be added to the Tool Rack. Added keywords will allow additional items to be placed on this block.
    S:AdditionalTools=sprayer, wand, rod, scepter, wrench, screwdriver, meter, handsaw, gun, cutter, scoop, soldering, painter, reader, shovel, grafter, pickaxe, pipette, magnifying, sword, axe, hammer, file, saw
}
```

Does it work for GT tools?

**Comment by Agrax** [comment]
Yeah. We know abt the config. But for some awkward reason it doesn’t seem to work on servers. It does what it should do on SP, but on MP it doesn’t work as it should, unfortunately

**Comment by Agrax** [comment]
We’re investigating possible solutions tho

**Comment by Agrax** [comment]
Asked Archie for a tool rack:
https://github.com/GregTechCE/GregTech/issues/779

**Comment by pyure** [comment]
I monitor this ticket periodically and check the Bibliocraft source/wiki.  It seems the mod is dead, and the author hasn't so much as responded to a ticket in a year.

I don't like closing un-resolved issues, but I don't want to keep them open indefinitely either w/o a likely solution.

I'm flagging the issue as Known Issue and closing it.
