### ISSUE TITLE
Nuclear Craft: Boron dust will not smelt into ingot.

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#250]
Version: 0.32

Electrolyzing Borax gives GTCE Boron dust, which cannot smelt into an ingot.

Key component required for the making of Tough Alloy-> most all of the building block components.

**Comment by Agrax** [comment]
@pyure 
we have 3 ways to proceed:
1. Make it materialIngot or w/e it's called
2. make the tough alloy recipe require dust instead of ingot
3. add a manual smelting recipe for the GT borax

**Comment by pyure** [comment]
I've added dustBorax to the dustBoron oredict, which will just generally allow borax dust to count as Boron.

**Comment by pyure** [comment]
Addressed in 0.34.
