### ISSUE TITLE
Nuclear Craft: Recipe for LEU-235 not working as designed

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#251]
Version: 0.32

The recipe for LEU-235 calls for 1 Uranium 235 ingot, 8 Uranium 238 ingots (or Uranium 238 Oxide).

Using /ct hand, the oredict for the uranium 235 ingot reads correctly for the recipe ingotUranium235, but the uranium 238 ingot reads as ingotUranium and fuelsRawUranium.  The NC recipe is looking for ingotUranium238
![leu-235](https://user-images.githubusercontent.com/8160400/49104313-a638a800-f24b-11e8-89e5-5524950e4ce9.jpg)

Also, the uranium-238 oxide recipe is at IV level to produce in the chemical reactor, is this correct?

**Comment by pyure** [comment]
As discussed (and a reminder to myself cuz I was hazy on the details)
* The U238 you're able to acquire doesn't have the correct oreDict to satisfy the LEU-235 recipe.
* I suspect its because you're using the deprecated GT-CE chain and will be disabling that.

**Comment by pyure** [comment]
Done in infitech-prototype-0.33.zip

(Lots more changes to fuels in the future I suspect however)
