### ISSUE TITLE
Nuclear Craft:  Update to 2.12F-1.12.2 release version

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#254]
Version 0.32

Could you please, as a matter of housekeeping, update NC to the 2.12F-1.12.2 release
It fixes an issue with the fission ports on the NC reactor not outputting the proper values for energy.
Tested locally and appears to have fixed the issue.

**Comment by Agrax** [comment]
Fixed via #260

**Comment by pyure** [comment]
Done in infitech-prototype-0.33.zip
