### ISSUE TITLE
Thermal Dynamics: Viaduct recipe

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#255]
Version: 0.32

The recipe for Viaducts cannot be completed because there seems to be no way to create Zephyrean Aerotheum.  Aerotheum does exist, it can be created from bees (9% chance) or a recipe with blizz powder.
Zephyrean doesn't exist.  So both would need to be added, something to create zephyrean and a recipe to create the combination.

![image](https://user-images.githubusercontent.com/8160400/49230811-84abfd80-f3be-11e8-9e09-b4247fa8c09c.png)

**Comment by Agrax** [comment]
Can confirm. The thing is none of us didn't even try to start tweaking viaducts

**Comment by Agrax** [comment]
Fixed via #259

**Comment by pyure** [comment]
Done in infitech-prototype-0.33.zip
