### ISSUE TITLE
Boots uncraftable?

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#256]
Trying to craft Iron Boots showed me that theres no easy way to get them. Intended?

**Comment by Agrax** [comment]
Show us the recipe, please? A screenshot would be much appreciated

**Comment by Agrax** [comment]
Well, can confirm. Can't make iron boots. Not intended

**Comment by Agrax** [comment]
Fixed via #257

**Comment by pyure** [comment]
Done in infitech-prototype-0.33.zip
