### ISSUE TITLE
Gendustry GT-Bees arent really implemented

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#262]
I didnt see an issue about this, but the added GT-bees for Gendrustry arent breedable (acc. to NEI) nor are they useful. It seems their combs can currently only be used for a slight increase of output at ore processing. This by far doesnt cover the time (it would take) to get them.

**Comment by Agrax** [comment]
The thing you're talking abt is gonna be released with the newest update. Maybe today, maybe tomorrow

**Comment by Gamejet** [comment]
wow that was quick

**Comment by Agrax** [comment]
Pyure is working on that thing for the last 2 weeks

**Comment by Gamejet** [comment]
thats awesome to hear, Im already hyped for the change :)
Btw I have a few minor suggestions, should I open issues for all of them?

**Comment by Agrax** [comment]
Yes, please. List them using github "task list". Thank you

**Comment by pyure** [comment]
Hi Gamejet.  The first overhaul pass on bees should be out in next version, hopefully w/i 24 hours.

You can definitely create issues for suggestions.  Its kind but not critical if you create separate issues for them (makes it easier for me to reject/accept suggestions piecemeal and release them piecemeal if some are easier than others)

**Comment by pyure** [comment]
Done in infitech-prototype-0.33.zip
