### ISSUE TITLE
Thaumcraft Plates

### ISSUE THREAD

**Issue by Arsonil** [pyure/infitech-prototype#263]
The crafted Thaumcraft Plates do not work for the Thaumcraft Quest "Thaumium Essentia Smelter"
When crafted i got the pink ones for the quest i need the dark violet ones.

**Comment by Agrax** [comment]
Is there a TC quest? O.o

**Comment by Agrax** [comment]
You might be playing either a really outdated version or unlocked smth via /bq_admin

**Comment by Arsonil** [comment]
i mean the quest in the thaumonomicon sry for this :P

**Comment by Agrax** [comment]
Oh, that’s worse. Good to know. Thank you kindly for your feedback. It’ll be revised someday

**Comment by pyure** [comment]
In the short term I believe we'll add a simple recipe to craft TC plates from GT plates.

**Comment by pyure** [comment]
Not sure if it will help since I'm not sure how to reproduce the problem, but I've added a recipe to get TC plates from GT ones.

**Comment by pyure** [comment]
Addressed in 0.34.
