### ISSUE TITLE
Thaumcraft Tools

### ISSUE THREAD

**Issue by Arsonil** [pyure/infitech-prototype#268]
Reference to #263

Thaumcraft Hoe,Pickaxe, Axe, Shovel and Sword wont work for the Thaumcraft! Quests (The ones in the Thaumonomicons).

Since the original Thaumcraft-tools are disabled there is no way to "hotfix" the problem for me.

**Comment by pyure** [comment]
I'll un-disable the originals and do the same transform fix I did with plates.  Thanks Arsonil.

**Comment by pyure** [comment]
This is partly but not fully addressed in 0.34.  The tools are (probably) now visible in 0.34.  They may even have recipes (not sure).
