### ISSUE TITLE
rubber sheets

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#271]
rubber sheets (necessary for quest) can only be produced by the rolling machine in the early game. I would suggest to add an inefficent alloy smelter recipe and a more efficent extruder recipe (theres none either) like in GT5.

**Comment by Agrax** [comment]
The issue is you can't even make rubber early game in the newest update you have :P But thanks, i'll look into that.

**Comment by Gamejet** [comment]
god damn, I didnt even follow the recipe line that far. Is that gamebreaking?

**Comment by Agrax** [comment]
Questline-breaking. Not game-breaking. It's just... nw. It'll be fixed in the next update

**Comment by Gamejet** [comment]
yeah I see, you can make most LV-machines without the need for rubber. Still good to see it fixed next update :)

**Comment by Agrax** [comment]
fixed via #270

**Comment by Agrax** [comment]
Didn't fix it. Added rubber ingot recipe, but no rubber plate recipe. I have a design, so im gonna implement it shortly

**Comment by pyure** [comment]
Done in infitech-prototype-0.35.zip
