### ISSUE TITLE
rubber tree spawning

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#272]
rubber trees try to spawn in weird locations:

![2018-12-03_23 31 44](https://user-images.githubusercontent.com/9951856/49407478-0b633080-f759-11e8-9055-c784adb16ad2.png)

**Comment by Agrax** [comment]
That's a GTCE issue. Need to be bumped to dev. Thanks for the issue

**Comment by pyure** [comment]
Known issue on GT side.  Closing cuz there's nothing we can do about it.

Good news is: Sometimes you find trees in weird places in real life too :)  blame floods!
