### ISSUE TITLE
Gregtech tanks are causing heavy frame drops

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#273]
When Gregtech tanks get hooked up to a pipe thats trying to constantly pump liquids into the tank they cause massive framedrops:

![2018-12-04_00 14 45](https://user-images.githubusercontent.com/9951856/49407674-ab20be80-f759-11e8-9313-fcfed069082e.png)

**Comment by pyure** [comment]
If and when this ever gets addressed (who knows) it will be included in a changelog.
