### ISSUE TITLE
Balancing: Servos are too hard to obtain early game

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#275]
Being able to pump liquids is really important early-game since one relies on steam.
However the only good method of pumping liquids (fancy fluid storage tanks have no auto-output)
is by either using a GT pump or a Servo which requires a GT pump.
I would suggest to get an easier way (early-game) to pump liquids.

**Comment by Gamejet** [comment]
yes you do get a single servo from a quest.

If thats your opinion on that topic so be it.
However one servo can only either pump water or steam out of a tank.
Giving only one servo effectively restricts the player not being able
to use steam tanks. Building those is being supported by the questing system though.

**Comment by Agrax** [comment]
We’ll discuss it in the dev channel. Let’s reopen it for now

**Comment by pyure** [comment]
@Gamejet here's what we came up with:
* You can use a faucet (Ceramics) for some fluid extraction.  Its super early-game.  It does shut itself off if its target destination is full however.  You MAY be able to automatically re-activate it with redstone signals
* You can use Liquid Hoppers from Pneumaticraft.  Be aware that this recipe will likely get nerfed in the future (its super weaksauce easy right now).  You may or may not have the means to orient it (I'm not sure which wrenches will play nice with it).  Its really slow compared to a servo.
* I'm kind of considering a very expensive pre-LV recipe for servos.

**Comment by Gamejet** [comment]
thanks for all the work you are putting into the pack, seriously :)
To be honest faucets are a big annoyance and Im one of those guys who dont like PneumatiCraft.
In infitech 2 tanks auto-outputted which was a nice way of cutting around this.
Now those tanks are missing creating a new need for pumping water and steam,
Personally coming from there the current early-game fluidtransport feels
a little unshaped. An ideal solution would be a pre-LV GT pump to me since
I always felt gt-pipes were looking good and underused. However an expensive pre-LV
recipe for servos looks like the best option you have tright now.

**Comment by pyure** [comment]
Not liking pneumaticraft is a personal choice.  That said, it doesn't please me as a really elegant solution.  On a trial basis I'm adding Buildcraft | Transport in version 0.34 (should hopefully be available in CurseForge soon)

BC is in alpha, and declares such with an annoying message when you log in.  I'm not sure where they're at on their roadmap towards a beta release.  I did test the fluid pipes and they seem to work as you'd think. 

I did not test the item or kinesis pipes.  

Fixed in dev (and probably next CF version within an hour or two)

**Comment by pyure** [comment]
Addressed in 0.34.
