### ISSUE TITLE
moving blocks in hand, bug or feature?

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#279]
Shift + rightclick moves certain blocks from the world into your hands. Then you can place them anywhere you want (with a rightclick). Bug or feature?
Carrying Crafting Table:
![2018-12-06_21 51 08](https://user-images.githubusercontent.com/9951856/49611334-84ed5f80-f9a1-11e8-967c-19eaeef9eb1e.png)

**Comment by TedKnudsen** [comment]
Feature via CarryOn.  

We'll be blacklisting some carries fwiw.

**Comment by pyure** [comment]
Feature via CarryOn.  We'll be blacklisting some carries fwiw (spawners etc if they aren't already)
