### ISSUE TITLE
tweaking: Magic Bees

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#282]
Magic Bees are too OP and need a tweak (e.g. Osmium Princesses produce Osmium nuggets straight away).

**Comment by ct-klein** [comment]
More to the point, there are two sets of Osmium bees.  One from Forestry and one from MagicBees.  The MagicBees one gives a nugget directly (16%), while the Forestry one has a 15% chance to drop Iridium/Platium/Osmium combs but there is no current use for the osmium combs.  The other two have recipes.

**Comment by Gamejet** [comment]
The other Osmium bee (which registeres as being from forestry) is from an additional beescript designed for GregTech with Gendustry afaik. MagicBees just needs those bees disabled that also exists in said beescript. But you are right, the entire beesystem (especially from that script) could use a little more love, but thats just a ton of work,

**Comment by pyure** [comment]
We have a partial fix for this in dev.  It removes all the bees that overlap with GT Ore bees.

There will still be some other bees, especially ones that produce mob-resources infinitely.  I'm slightly concerned about the ones that can generate dragon eggs and wither skulls.  Those might get addressed separately at a later time.

**Comment by pyure** [comment]
Released (partial fix) in infitech-prototype-0.36.zip
