### ISSUE TITLE
Primitive bricks - hammer compatibility 

### ISSUE THREAD

**Issue by Earthyx** [pyure/infitech-prototype#283]
![2018-12-11_14 06 01](https://user-images.githubusercontent.com/45801384/49827266-8aa2c680-fd4e-11e8-90bb-a717b0772d85.png)
![2018-12-11_14 06 07](https://user-images.githubusercontent.com/45801384/49827277-9098a780-fd4e-11e8-8a32-51ffa94cb4f5.png)

**Comment by Gamejet** [comment]
this might be related? https://github.com/GregTechCE/GregTech/issues/453

**Comment by pyure** [comment]
Possibly fixed by Arch.  Still need to confirm before closing the issue.

**Comment by pyure** [comment]
Released (probably) in infitech-prototype-0.36.zip
