### ISSUE TITLE
Make impure ores easier to work with

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#284]
So, if I'm correct, "impure" ores such as limonite, chalcopyrite, tetrahedrite, and malachite don't double in foundry, just give 1.5 ingots. I did make a similar issue earlier but this is a proposed solution, I guess. 1.5 ingots worth of fluid doesn't very well for automation or anything similar, making impure ores a pain to work with because they make barely enough liquid that you have to break and replace the foundry to clear the tank, casting into nuggets doesn't even work. So I suggest that you change them to produce 208 molten metal, which casts out into 1 ingot and 4 nuggets into 1 ingot and 4 nuggets and a little useless extra

**Comment by RedBlockFilms** [comment]
This doesn't mean that you can automate it, but it does mean that you don't have to break or mess with that tiny bit of molten metal

**Comment by Agrax** [comment]
1,5+1,5=3

**Comment by RedBlockFilms** [comment]
I realize this, but that also means you only need to gather only even amounts of metals

**Comment by Agrax** [comment]
Exactly. Or just smelt an odd amount of ores. That's how it's supposed to work. Because it's pre-LV it's supposed to be a pain in your life

**Comment by TedKnudsen** [comment]
Agreed with Agrax.  Foundry has some benefits but a draw back is that its got automation and convenience concerns.  Its supposed to be an optional diversion from the main path.

**Comment by pyure** [comment]
Agreed with Agrax. Foundry has some benefits but a draw back is that its got automation and convenience concerns. Its supposed to be an optional diversion from the main path.
