### ISSUE TITLE
Iron doors allow for easy iron duplication.

### ISSUE THREAD

**Issue by Earthyx** [pyure/infitech-prototype#285]
Recipe takes 6 iron plates and creates 3 doors. Each door macerated creates 6 iron dust. Recipe needs adjustment

**Comment by Agrax** [comment]
It might be already fixed on GA side. Im not certain, but the issue is known to me

**Comment by pyure** [comment]
Apparently fixed in a recent version of GT-CE.  When GA updates we can move to that version.

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
