### ISSUE TITLE
chunk loaders

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#286]
Thanks to ftb-utilities (thats the mod that allows you to claim chunks) chunk loading is super easy (shift + left-click on the claimed-chunks map will load chunks). I would suggest to nerf that and to add a slightly costly way to load chunks.

**Comment by Agrax** [comment]
No. Chunk loading is just a convenience. That was a mistake on our part to introduce expensive chunk loading in IT2

**Comment by pyure** [comment]
Thanks Gamejet. I've been considering some notion of a tip-of-the-day, this would be an appropriate one.

(Also, yeah, chunkloading is a game requirement rather than a game-design element.  Ideally all chunks would just be loaded permanently. )
