### ISSUE TITLE
Chad Machine Recipe

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#287]
Currently you can't make chad in any way except mortar, and the next up way to make paper is LV, right after you need a ton of paper, so a steam machine method would make sense

**Comment by Gamejet** [comment]
I feel like its fine the way it is. You would need ~ 3 to 4 stacks of paper to advance to the point where you can make paper efficiently. However thats a balancing question and therefore hard to answer.

**Comment by Agrax** [comment]
And that’s a question that ought to be answered by us, game developers.

We wouldn’t mind adding an inefficient, but automatable chad recipe. Like 3 canes-> 2 chad or smth

**Comment by RedBlockFilms** [comment]
That would be perfectly fine with me. As long as I don't have to spend so much metal on grindstones, anything works

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
