### ISSUE TITLE
Pneumaticraft is very laggy

### ISSUE THREAD

**Issue by RedBlockFilms** [pyure/infitech-prototype#288]
It seems that inserting an item or pressure into the pressure chamber causes an obviously drop in frames, about 40 for me. This lag doesn't go away until I completely remove the pressure chamber and things connected to it

**Comment by RedBlockFilms** [comment]
It also causes a noticeable TPS drop in the surrounding area

**Comment by RedBlockFilms** [comment]
And as if to make matters worse, any pressure tubes I connect can't be broken anymore

**Comment by Agrax** [comment]
i feel like we need to update our pneumaticcraft. Seems like our version is 3 versions old

**Comment by pyure** [comment]
And they do frequent performance passes too.  We'll make PC updates more of a priority.

**Comment by pyure** [comment]
Marking this done in dev due to mod updates which may or may not really help.

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
