### ISSUE TITLE
BC: gears

### ISSUE THREAD

**Issue by Gamejet** [pyure/infitech-prototype#290]
the new BC gears could be replaced by GT gears for a smoother balance:
EDIT: for some reason the BC recipe ends up giving you the AE gear.

![2018-12-16_16 18 36](https://user-images.githubusercontent.com/9951856/50055388-87447c00-014e-11e9-916d-dfb43a452fd1.png)
![2018-12-16_16 21 44](https://user-images.githubusercontent.com/9951856/50055407-c2df4600-014e-11e9-96af-74a4df8ada5e.png)

And when you are at it you might also want to change the TE recipe (so that one needs tools):
![2018-12-16_16 22 08](https://user-images.githubusercontent.com/9951856/50055425-0934a500-014f-11e9-831d-b0392b452fe4.png)

**Comment by pyure** [comment]
Will disable any gear recipes that are also covered by GT.  
For gears that don't have a GT counterpart, we'll tweak the recipes.

**Comment by pyure** [comment]
I feel like this is more or less already fixed.  I checked wooden and iron gears they seem to be fine
