### ISSUE TITLE
NuclearCraft: Fusion Core recipe

### ISSUE THREAD

**Issue by ct-klein** [pyure/infitech-prototype#298]
Version: 0.34

Just a reminder to Xavion, the recipe for the fusion core currently has 2 NC chemical reactors as part of it which have been disabled in the pack.
![image](https://user-images.githubusercontent.com/8160400/51137189-4b174080-180c-11e9-965f-b9e9909adf3e.png)

**Comment by pyure** [comment]
@Xavion3 any preference for how this gets addressed?

My best guess would be to replace those disabled Chem Reactors with either GT Machine Casings or with GT Chemical Reactors.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.38
