### ISSUE TITLE
wood logs have the wrong descriptions

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [pyure/infitech-prototype#299]
basically this
![image](https://user-images.githubusercontent.com/40670872/51137820-2e006300-1848-11e9-9f1d-3af172156522.png)
i pressed f3 H to see the other descriptions, so basically its only the carbon value description that is wrong

**Comment by pyure** [comment]
I need this clarified. How is the 1,600 "wrong"?

**Comment by Agrax** [comment]
For most ppl carbon value=burntime in ticks

**Comment by pyure** [comment]
Mechanically they really are distinct though; it just so happens that they're usually the same.

This isn't a bug, its just unusual.  We can re-open or create a new ticket if there's an actual problem with the values themselves.
