### ISSUE TITLE
More GT quest information

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#301]
A guy recently told me abt an issue he's having with quest descriptions:

"As someone who is okay with jumping on to any pack my friends play, I feel there is a lack of information on how to set up GregTech machines. I was wondering if you could add more to your questbook under the quests about how to set up each machine, and maybe a little bit about how they work together. I get the general idea from reading NEI but it'd be nice for a worded explanation, as I and some other might learn better that way."

An other guy, PoptartOverlord-Xabedo thinks that our quests need more exhaustive descriptions, because for now they provide almost no useful content.

**Comment by pyure** [comment]
Its good feedback.  I'm closing the ticket because there's no "specific" work to be done other than an overall goal to improve the quest content.
