### ISSUE TITLE
Weird stone macerations

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#302]
vanilla granite -> black granite dust
diorite -> andesite dust

No clue what's causing this

**Comment by pyure** [comment]
That wasn't really a great answer.

I've loaded up the mod with just GT-CE.  It seems to be native to the mod.

**Comment by pyure** [comment]
I've created a ticket with Archengius.  If he agrees its an error and elects to fix it I'll leave the ticket open pending that fix.

https://github.com/GregTechCE/GregTech/issues/526

**Comment by pyure** [comment]
Released (apparently) in infitech-prototype-0.36.zip
