### ISSUE TITLE
[suggestion] add reauth

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#303]
https://minecraft.curseforge.com/projects/reauth

**Comment by pyure** [comment]
This is really super client-specific.  I'm surprised you can even mod this at a pack level.

Has anyone had complaints that this helps with?

**Comment by Agrax** [comment]
A guy called xabedo or smth. Someone from Rong’s discord. Lemme get you in touch with him

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
