### ISSUE TITLE
Zencessories for our biofuel

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#304]
https://minecraft.curseforge.com/projects/zencessories

**Comment by pyure** [comment]
Do we really mean biofuel this time?  Last time we tinkered with zencessories it was for methane.

**Comment by Agrax** [comment]
Ok. It might be methane

**Comment by pyure** [comment]
Ultimately this isn't something I want to put time into in the near or medium future.

**Comment by Agrax** [comment]
Kinda dissapointed after all the fuss i went through
