### ISSUE TITLE
[Suggestion] Add a Way to Manufacture Sand

### ISSUE THREAD

**Issue by Bagabundoman** [pyure/infitech-prototype#310]
Currently, macerating cobblestone makes stone dust, and macerating gravel makes flint. The hammer will turn cobblestone into gravel, but gravel is unaffected. The only way we can find through JEI to make sand really is through botania. It seems silly that with all these machines there is no way to make stone -> sand, it's a common modded recipe and it seems missing.

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
