### ISSUE TITLE
Recipe for thaumium tools 

### ISSUE THREAD

**Issue by Waisse** [pyure/infitech-prototype#312]
They don't have one, and they are needed for a research.

**Comment by pyure** [comment]
@Waisse I'll probably do the 1-durability trick for these.  I hate to bring back the "useless" tools, but I also hate the idea of trying to track down all the research that is affected.  

(That said, if I suddenly get non-lazy, you'll find a bunch of GT toolhead TC recipes)

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
