### ISSUE TITLE
Vanilla gold tool

### ISSUE THREAD

**Issue by Waisse** [pyure/infitech-prototype#313]
They need a recipe
https://i.imgur.com/i8Ri1aN.png

**Comment by pyure** [comment]
I've changed the TC Recipe to use GT golden tool heads.  
Heads up: I can't figure out a way to make the thaumonomicon ingest new recipes.  So I'm adding a tooltip to the book that reminds players to check JEI.

Good news is it does remove the old recipe from the book, so at least there's no actual conflict.

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
