### ISSUE TITLE
[Bug] Crafter T3 requires crafter T3 to make

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#316]
https://puu.sh/CCDNY/2257410364.jpg

Rn it looks like that
`recipes.addShaped(crafter3, [
	[mvRobotArm, craftingTable, mvMotor],
	[o_goodCircuit, crafter3, o_goodCircuit],
	[<ore:plateAluminium>, craftingTable, <ore:plateAluminium>]]);`

**Comment by Agrax** [comment]
Plus GT electric motor's metaitem calls are incorrect

**Comment by Agrax** [comment]
Both fixed via #317

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
