### ISSUE TITLE
Weird smeltings

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#318]
GT issue, autocreated recipes:

[Magnetic steel dust](https://cdn.discordapp.com/attachments/432560981898559498/539089604457005066/Zrzut_ekranu_2019-01-27_15.28.56.png)

[Magnetic neodymium dust](https://cdn.discordapp.com/attachments/432560981898559498/539089598106828800/Zrzut_ekranu_2019-01-27_15.28.42.png)

**Comment by Quantum64** [comment]
Getting 404s on those images.

**Comment by Agrax** [comment]
Righto. My bad

**Comment by Quantum64** [comment]
Ah, I see. I'll take a look at this tonight.

**Comment by Agrax** [comment]
I think Arch is already workin on that. Not sure tho

**Comment by pyure** [comment]
Released in infitech-prototype-0.36.zip
