### ISSUE TITLE
Cannot craft ingots out of nuggets for any metal

### ISSUE THREAD

**Issue by Archengius** [pyure/infitech-prototype#330]
presumably GA issue

**Comment by Agrax** [comment]
Yeah, we think so too. 90% of cases if smth is broken, it’s GA’s fault

**Comment by Archengius** [comment]
even if it IS GA issue:
1) i'm not going to fix it
2) i'm not going to maintain GA shit any further
3) it's exactly on YOU to fix it for your pack

**Comment by pyure** [comment]
Thanks for the report Arch; we'll manually add nugget/ingot recipes pending a cleanup.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.38
