### ISSUE TITLE
Advanced Rocketry's Lathe allows cheating by creation of 2 rods from one ingot pre-LV, where it should be possible on MV only

### ISSUE THREAD

**Issue by Archengius** [pyure/infitech-prototype#345]

**Comment by pyure** [comment]
This is a problem pervasive to AR.  I'm not sure what I want to do about it other than just making sure all the AR machines are MV-plus (which we should do at the very least anyway)

**Comment by Agrax** [comment]
Now even an LV lathe produces 2 rods. Can tweak accordingly

**Comment by pyure** [comment]
We still don't have an actual design for these machines.  We can make them just be "alternative rod makers" or w/e, but ideally it would fit a different niche.

**Comment by JoelLaviron** [comment]
This issue is solved no? Since Vulpes Machine structures are now only craftable with assembler HV and stainless steel. (Old crafting table recipe with 4 iron plate is still listed in JEI but doesn't seem to work).

**Comment by pyure** [comment]
Technically yeah its resolved.  In truth I also want to identify better uses for these machines.  But I'll spin up an internal issue to track that, thanks for pointing it out.
