### ISSUE TITLE
Railcraft Tanks lack localization

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#364]
IT3: 0.39.1

**Comment by pyure** [comment]
also: gauges, valves, walls, railcraft.post.metal

**Comment by ct-klein** [comment]
Tested with RC 12.0.0 (Railcraft-12.0.0.jar) and all of the RC localization issues were resolved in 0.39.1 pack

**Comment by pyure** [comment]
Will close on next version release

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.40.zip
