### ISSUE TITLE
Bronze Age - bug on Little plumber's set

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#365]
Hello,

The Bronze Age quest "Little plumber's set" cannot be completed because it references gregtech:fluid_pipe_bronze/1 but it seems to no longer exist. We cannot give it to us with /give either. The existings pipes are tiny, small, medium or large. We have only crafted the small bronze pipes, so I cannot guarantee that it doesn't work with the other sizes.

Here a screenshot showing the issue:
![QuestingBug](https://user-images.githubusercontent.com/26551406/54493206-6f0b0700-48cd-11e9-9fd9-c56f46f10613.png)

Thanks for you work on infitech 3, we enjoyed a lot infitech2 :)

**Comment by pyure** [comment]
Hiya JoelLaviron,
Our recent update to new GT versions seriously broke our quests.  Good news:  we're currently in the process of switching our quests mod to another mod, and a new IT3 version will be released shortly.

That said I'll make sure this isn't also broken in the new questline :)

**Comment by JoelLaviron** [comment]
Great, thanks
