### ISSUE TITLE
Can't craft primitive bricks

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#366]
Hello, 

I seem to experience issue #283 again on 0.39.1.
![2019-03-17_18 53 46](https://user-images.githubusercontent.com/19927604/54495761-28c2a180-48e7-11e9-954e-d68e680d2291.png)
![2019-03-17_18 56 15](https://user-images.githubusercontent.com/19927604/54495792-7e974980-48e7-11e9-94e4-b428ffe4fced.png)

There are also other recipes that are affected, they all seem to involve crafting a Foundry object: I could not craft a bronze cauldron, refractory casing or a mold crafting station using generic tools. Only the Darmstadtium version would work.

**Comment by pyure** [comment]
Yikes, confirmed.

**Comment by pyure** [comment]
Known issue with the GT tool oredicts.  I'll replace all instances with a fugly known fix.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.40.zip
