### ISSUE TITLE
crash when trying to place sticky resin in primitive blast furnace

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#367]
Hello,

I tried using sticky resin in the fuel/charcoal slot of the primitive blast furnace (I didn't really expect anything to happen, but I tried anyway).
The client crashed, see attached log file. 
[crash-2019-03-17_19.25.54-client.txt](https://github.com/pyure/infitech-prototype/files/2975545/crash-2019-03-17_19.25.54-client.txt).

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.40.zip on curseforge.

Thanks for all the great feedback @TLaviron
