### ISSUE TITLE
Investigate missing recipe for Foundry revolver

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#373]

**Comment by pyure** [comment]
I don't think this is actually an issue; parts are made via Foundry casting.

**Comment by pyure** [comment]
Metal for casting might be the problem.  
Todo:
* Confirm our liquid steel works fine
* Ensure we can melt steel (only) with an advanced crucible

**Comment by Ligi89** [comment]
additional info, the gun part molds don't go in the slot where the  currently working molds (plate, gear, etc...) go in the metal caster, so just the ability to melt steel may not be enough of a fix.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
