### ISSUE TITLE
Disable Forestry Centrifuge in favour of GT

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#374]
Make sure we port any missing recipes.  
Mark the machine as Disabled; ppl will definitely search for it in JEI.

**Comment by pyure** [comment]
Looks like there are more than a dozen combs that have Forestry-centrifuge specific recipes which need converting to GT.

**Comment by Archengius** [comment]
why

**Comment by pyure** [comment]
If we disable the centrifuge, need to make sure the actual outputs from Forestry (on, say, combs) correlates to the expected outputs from GT (sensibly, at multiple tiers)
