### ISSUE TITLE
Quest: "Some tools are just better than others" issues

### ISSUE THREAD

**Issue by diabaulau** [pyure/infitech-prototype#376]
- The wire cutter has no generic filter, and thus requires the darmstadtium one
    - The wrench is indicated as being consumed by the quest, while it is not

I ran into these issues while rushing the new quests in order to catch up with our advancement.
I tried giving the wrought iron wire cutter to other persons on the team, but it did not update the quests (the other tools worked fine)

**Comment by pyure** [comment]
Thanks for the feedback @diabaulau.  By any chance was the File also weird?

**Comment by diabaulau** [comment]
I just checked, and the quest has marked the file as done. Maybe because it was a file made BEFORE the update ?

**Comment by TedKnudsen** [comment]
Possibly.  I've made some fixes either way.  Now if I could only figure out why the Scoop quest keeps getting marked as completed for no reason ;)

**Comment by pyure** [comment]
Possibly. I've made some fixes either way. Now if I could only figure out why the Scoop quest keeps getting marked as completed for no reason ;)

**Comment by pyure** [comment]
Fixed in 0.41, although there are definitely persisting issues with stuff related to tools triggering quests.
