### ISSUE TITLE
Slightly improve stats for Thaumium tools

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#381]
Per Divran

**Comment by Divran** [comment]
So we remember, I recommend keeping all stats the same except mining level, just bump that from 2 to 3 and it should be balanced compared to cobalt.

**Comment by pyure** [comment]
Bit worried its a hair too buff right now, but willing to keep an eye on it.

**Comment by pyure** [comment]
Fixed in 0.41
