### ISSUE TITLE
Tank valve not craftable

### ISSUE THREAD

**Issue by Ligi89** [pyure/infitech-prototype#382]
It appears the Tank Valve block from the Fancy Fluid Storage mod can not be crafted.
Maybe requires specifically the "Darmstadtium" wrench?

Using iron wrench:
![2019-03-19_22 03 59](https://user-images.githubusercontent.com/10133628/54641802-55b3b780-4a93-11e9-8798-0515efb16653.png)

Using a cheated-in Darmstadtium Wrench:
![2019-03-19_22 09 46](https://user-images.githubusercontent.com/10133628/54642032-f1ddbe80-4a93-11e9-8727-5dc644424eee.png)

**Comment by pyure** [comment]
Thanks Ligi.  Black0305 has corrected this in dev.

**Comment by pyure** [comment]
Fixed in 0.41
