### ISSUE TITLE
Missing recipe for integrated circuit

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#388]
Hello,

There does not seem to be a recipe to craft the integrated circuit (the one used in multiple gregtech machines to configure recipes).
At the very least, the recipe does not appear in JEI.

**Comment by pyure** [comment]
Confirmed (By the GT dev this morning).  I'll try to release a fix w/i next 8-10 hours or so.

**Comment by pyure** [comment]
Fixed in 0.41
