### ISSUE TITLE
Ring of the mantle uncraftable

### ISSUE THREAD

**Issue by Ligi89** [pyure/infitech-prototype#407]
Botania Ring of the Mantle currently looks like it's tweaked somewhat, as accorindg to JEI it uses a Gregtech Aluminium pickaxe as a component.

The recipe does not seem to work, however:

![2019-03-24_18 01 34](https://user-images.githubusercontent.com/10133628/54882879-e1945d80-4e5e-11e9-9eb4-71d0fdf14530.png)

**Comment by pyure** [comment]
Thanks Ligi I'll have a look (again :p )

**Comment by pyure** [comment]
Oh yeah, Arch removed gold tools.  (Don't blame him: gold would be a terrible tool material.)

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.42b
