### ISSUE TITLE
crash when gregtech wood pipe burned

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#408]
Hello,

I encountered a server crash, which from the log output I assume it was caused by a wooden pipe having burned but still trying to act as a pipe.
(My guess is a wooden pipe providing water to a steam boiler was momentarily filled with steam produced by the boiler, which is why it caught fire).
This left the world save in an unusable state, as it would crash as soon as it started, so I restored a backup.

[crash-2019-03-24_18.27.52-server.txt](https://github.com/pyure/infitech-prototype/files/3000639/crash-2019-03-24_18.27.52-server.txt)

I have attached one of the crash logs, If needed I can provide the broken save file.

**Comment by pyure** [comment]
TLaviron any chance you can try to reproduce it before I bring it to the GT dev?

**Comment by pyure** [comment]
Actually don't worry about it.  Looking at the log, definitely looks like GT fighting forge.

**Comment by pyure** [comment]
https://github.com/GregTechCE/GregTech/issues/675

**Comment by pyure** [comment]
Done in infitech-prototype-0.43b
