### ISSUE TITLE
FMB + Chisel: Agrax-induced issue

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#412]
https://github.com/pyure/infitech-prototype/blob/a26a2023c693ae248d7369642ebfb801ccc4bdaa/config/microblocks.cfg#L171

Should be `"chisel:planks-dark-oak":0-14`

My fault. Please, There's a dash missing because of my own error.

**Comment by pyure** [comment]
Thank you.  Fixed by Black0305 in dev.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.42b
