### ISSUE TITLE
[Suggestion] DR lens greggification

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#414]
https://imgur.com/a/YCUCaEt

It could use a green lens from GTCE (<ore:craftingLensGreen>) and be made in an assembler. I don't question your choices. It's just a suggestion. Close it if you feel like it doesn't bring anything new.

(You could greggify other machines a tiny tad bit too [a pedestal could use plates or smth]).

**Comment by pyure** [comment]
Deep Resonance is slated for tweaks in Beta.  If this particular recipe is causing problems on your server we'll tweak it in Alpha.

**Comment by Agrax** [comment]
No issues per se. That's just a greggification suggestion, nothing more

**Comment by pyure** [comment]
Added lens/assembler recipe.  Note that most of the machines are already a bit gregged via the Resonating Machine Frame, which is a core component of most machines.  We'll pursue less-lazy tweaks for the other machines during beta or on a upon-suggestion basis.

(Also added pedestal/plate recipe)

**Comment by Agrax** [comment]
I can greggify other machines if i find some time

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
