### ISSUE TITLE
"Tooling up!" quest

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#415]
The quest uses the old wrought iron tools that had the "Sharpness" innate enchantement. Arch changed that few releases ago. This can be fixed by just redoing the requirements. Idk- maybe this is fixed in dev. As it stands now (i think) it can't be completed (im aware that our versions differ). Close if the issue is redundant.

**Comment by pyure** [comment]
Thanks; this particular quest is already fixed in dev.  Its probably worthwhile not to submit any quest issues until after next release since we did full QC pass on it this week during Jason's streams and there have been a lot of fixes.
