### ISSUE TITLE
Update CEU

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#422]
https://minecraft.curseforge.com/projects/ceu/files/2691044

**Comment by pyure** [comment]
Was this tested with Infitech3 version 0.42b

**Comment by Agrax** [comment]
Whaddya mean? Tested if works with 0.42b?

**Comment by pyure** [comment]
Yes, to confirm that the modpack still loads and that there isn't any (obvious) regression problems (such as machines crashing the modpack)

**Comment by Agrax** [comment]
No. It was not tested

**Comment by pyure** [comment]
Reminder to self: basic QC required, then merge.

**Comment by pyure** [comment]
Fixed script issues after port.  There are some new machines (ICEF etc).  I have no idea what these do.  CEF/IC2 compat maybe.  I didn't add script handling for them.

**Comment by Agrax** [comment]
Infinite CEF and Infinite CEU maybe?

**Comment by pyure** [comment]
I actually thought so too for a minute but there are tooltips on the machines suggesting they're for IC2.  They're disabled by default, probably because that mod wasn't detected.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
