### ISSUE TITLE
[Suggestion] Battery oredicts

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#424]
Sodium, cadmium and lithium batteries are oredicted as <ore:batteryLVAll>, but mercury and acid aren't. Can you add oredicts to these two batteries, please?

I've had a player be discontent by the fact that his mercury battery didn't complete the quest.

**Comment by pyure** [comment]
Reviewed recipes, doesn't seem to be any logical conflicts for that oredict.  Added.

**Comment by pyure** [comment]
Done in infitech-prototype-0.43b
