### ISSUE TITLE
Look into adding Garbage Bins Reborn

### ISSUE THREAD

**Issue by pyure** [pyure/infitech-prototype#426]
* Confirm we have no other alternative void-liquid mechanisms (other than BC void pipe)
* Figure out a recipe that is somehow equivalent but less annoying than making a Packer.

**Comment by TedKnudsen** [comment]
Yeah I kinda thought NC had a  bin for this too.  I won't be able to convince Arch that's its reasonably accessible.  I have to think on whether I care about this task.

**Comment by pyure** [comment]
Yeah I kinda thought NC had a bin for this too. I won't be able to convince Arch that's its reasonably accessible. I have to think on whether I care about this task.

**Comment by pyure** [comment]
Not doing this; we do have alternatives and they're sufficiently early game.
