### ISSUE TITLE
Copper Quest oredic

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#429]
Add new GT copper ores (bornite, enargite, cuprite, chalcocite) to oredic `<ore:copperQuestOres>`, so that these new copper-bearing minerals can complete the "Ore Variety" quest

**Comment by pyure** [comment]
Will do this for any variants that are overwhelmingly copper (which may be all of them, not sure).

**Comment by Agrax** [comment]
Bornite: Cu5FeS4
Enargite: Cu3AsS4
Chalcocite: Cu2S
Cuprite: Cu2O

As a reference

**Comment by pyure** [comment]
Most of those are really questionable.  Do we already have a (shoddy) precedent with Tetrahedrite?

**Comment by Agrax** [comment]
That was your idea in the first place: to make all iron, copper and tin-bearing minerals be usable in this quest. Just as a reminder

**Comment by pyure** [comment]
Yeah that rings a bell.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
