### ISSUE TITLE
Steel and damascus steel can't be melted in Foundry

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#430]
As in the title. The funny thing is that some higher tier metals (titanium) can be melted in Foundry without any issue

**Comment by McRayJason** [comment]
I would personaly really left Foundry only to be able to melt low tier metals.

**Comment by pyure** [comment]
Just to clarify, it can "melt" high-tier things, but not "make" them.

Both ideas are fine, we'll natter about it and make it consistent one way or the other.

**Comment by Agrax** [comment]
Im fine either way. I don't want to "make" steel in foundry. I just suggest to make it able to create steel tools

**Comment by Agrax** [comment]
Cobaltite DUSTS can't be melted either

**Comment by McRayJason** [comment]
Well no dusts can be melted in foundry

**Comment by Agrax** [comment]
Well, don't mind me then. I just your friendly, neightbourhood retard

**Comment by pyure** [comment]
Once upon a time dusts were meltable.  I removed it because they no longer generate a single ingot, and I don't want to try to maintain a synced map of which material dusts produce how many nuggets

**Comment by Agrax** [comment]
I know that, but i forgot abt this one

**Comment by pyure** [comment]
Its more work but I agree with Jason. 

I've removed 70% of the metals that can be melted or worked with in the Foundry Crucible and Caster.  The "hardest" stuff that can be worked with are things like Cobalt and Compressed Wrought Iron.  Anything related to steel, most alloys and anything exotic is now removed.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
