### ISSUE TITLE
Itemducts too early in quest line

### ISSUE THREAD

**Issue by McRayJason** [pyure/infitech-prototype#431]
I know this is beta stuff, but i do not care.

ItemDucts can be made only in Assembler which is further down the quest line. I suggest moving the ItemDucts quest to Assembler optional quests

**Comment by pyure** [comment]
I mentioned...somewhere...that Itemducts is in a broken place.  I have an internal task to fix this.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
