### ISSUE TITLE
[Suggestion] Forestry fire pit

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#432]
LV compressor: automating wood piles (8 wood-> 1 wood pile)
MV or even HV packager ->cheaper wood piles

**Comment by pyure** [comment]
We can do LV.  I don't want to do MV/HV because it competes with later techs (Pyrolyse, even coke ovens)

**Comment by Agrax** [comment]
You can then play with it a bit and make smth like that (if you so desire)
Steam: automating wood piles
LV: cheaper wood piles (7 wood instead of 8?)

That's up to you

**Comment by pyure** [comment]
Will just do the automation.  If there's a balance problem with the wood piles I'd rather address it with the wall configs than via tiering (pending a different argument we're not considering)

**Comment by Agrax** [comment]
Naw, it's totally fine. Charcoal wall scripts are well-balanced

**Comment by pyure** [comment]
Done in dev, but obviously its deprecated quickly by any autocrafting mechanism.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
