### ISSUE TITLE
TF shears uncraftable

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#435]
https://imgur.com/a/yjObOko

TF shears recipes still use the wildcard syntax that doesn't work for `any` tool. It needs to be updated, like was the rest of scripts in order to work

**Comment by pyure** [comment]
Reminder to self: we have both "shears" and thermal-foundation shears scripts.  The former may already be deprecated.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
