### ISSUE TITLE
[Suggestion] Backpacks

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#436]
Black tweaked backpack upgrades' cost (new materials). Now for example a wooden upgrade uses iron plates. For the sake of consistency rename the upgrades:
- wooden-> iron
- stone -> steel
- iron -> aluminium
- gold -> stainless steel
- diamond -> titanium

**Comment by pyure** [comment]
Can you clarify what you mean by rename?  Do you mean literally change the end-user name that they see?

**Comment by Agrax** [comment]
Yes, exactly. Indeed.

**Comment by pyure** [comment]
I'm not sure that's "safe" per se.  Front end names are governed by localization.  If the current names make no sense, I'd rather tweak the recipes themselves a bit, so that the Stone recipe was Stone + Steel, Iron was Iron + Aluminium, etc.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
