### ISSUE TITLE
[Suggestion] Resonating ore

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#444]
Add resonating ore as a rare loot from Redstone Veins:

https://github.com/pyure/infitech-prototype/blob/master/config/gregtech/worldgen/overworld/redstone_vein.json

It's kinda rare as of now. And it spawns like vanilla ores: everywhere, but nowhere

**Comment by pyure** [comment]
I'm not super-opposed to putting this into a GT vein but can you propose a vein which is both thematic (which redstone feels) but is also relatively under-used (which redstone is not) ?

**Comment by Agrax** [comment]
Thorium? Assuming the resonating ore is *kinda* radioactivish? Dunno

**Comment by pyure** [comment]
Talked to devs.  Added to Molybdenum for now.  Nobody cares about molybdenum (for a long time anyway)

Concentration is approximately 1% in overworld (maybe too high).  3% in End (probably too high)

**Comment by pyure** [comment]
I've disabled overworld, End and other-dimension generation of the ore. I've actually left the Nether generation intact.  Will monitor to see if it causes problems.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
