### ISSUE TITLE
empty fluid cells used do not stack with unused ones

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#445]
Hello,

It appears that fluid cells that are emptied still have some nbt attached, unlike freshly crafted ones, causing them to be unstackable.
![2019-03-31_14 37 52](https://user-images.githubusercontent.com/19927604/55289143-bfe92800-53c2-11e9-9f87-85a7b42d7c54.png)

In this case, I have emptied some oxygen cells by clicking on a fluid input slot of a machine, and some hydrogen cells by putting them in a multiblock input hatch.
the two kind stack together, but not with empty cells not yet used.

**Comment by pyure** [comment]
@TLaviron I'll ask Archengius.

If he declines, I might be able to add a shapeless recipe that crafts emptied cells into new (deletes nbt).  Not sure if that would be sufficient for your use-case.

https://github.com/GregTechCE/GregTech/issues/696

**Comment by pyure** [comment]
The GT fluid cells use a forge implementation which has limitations that Arch doesn't want to mess with.  I've added shapeless recipes to clear the nbt of cells.  Pros: you can empty cells on the fly (which I like).  Cons: still annoying, and not great for automation.

**Comment by pyure** [comment]
Pros: Knowing Arch, he'll get annoyed with my solution and provide a real one.

**Comment by TLaviron** [comment]
Great, that will allow me to merge empty cells to avoid having different stacks of empty cells.
We're not using a lot of automation (yet) at the moment, we will see if there are any issues with it when we get there.

**Comment by pyure** [comment]
Done in infitech-prototype-0.44
