### ISSUE TITLE
Balance wooden pipe recipes

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#446]
Hello,

I have noticed that the small and medium wooden pipe recipes both produce one pipe for the same amount of materials.
![2019-03-31_14 42 33](https://user-images.githubusercontent.com/19927604/55289194-8533bf80-53c3-11e9-9da1-e7555fd8dc3d.png)
I suppose it would make sense to have them balanced like the metal pipes, so there can be a reason to chose one or the other.

Additionally, the tiny and large variants of the wooden pipes are not craftable (since they can't be extruded).

**Comment by pyure** [comment]
Brought to Archengius's attention. If he declines I can make custom recipes.

https://github.com/GregTechCE/GregTech/issues/697

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.45
(Still no tiny/huge yet, but I'm willing to wait to see if the dev has an in-mod approach)
