### ISSUE TITLE
[Suggestion] A nuts idea

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#457]
Add pam's nuts to GT fluid extractor as a way to get seed oil:
- peanut (60mB)
- pecan (75mB)
- pistachio (75mB)
- hazelnut (60mB)
- almond (75mB)
- chestnut (75mB)
- walnut (75mB)

**Comment by Ligi89** [comment]
That idea is nuts!
Nut gonna say they are bad, though :)

**Comment by Agrax** [comment]
#468

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.45
