### ISSUE TITLE
Bees for redstone too buff?

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#459]
In newer version you get 12 redstone for macerating redstone. Bees multiply this amount by 4. You get 48 redstone for one ore. Isn't it *slightly* too buff?

**Comment by TedKnudsen** [comment]
Feels too buff.  On the same note, I'm pretty sure are other way-to-buff comb outputs.  Titanium BEEing one of them.

**Comment by pyure** [comment]
Feels too buff. On the same note, I'm pretty sure are other way-to-buff comb outputs. Titanium BEEing one of them.

**Comment by Agrax** [comment]
With redstone pollen you get even 6.

12x6 = 72 redstone dust for one ore xD

Do keep in mind that tungstensteel grinding solution gives 32 tiny piles of rare earth PER crushed redstone.

12x32= 384 tiny piles

384:9= 42x rare earths PER ORE BLOCK

**Comment by pyure** [comment]
Yeah.  It was always broken for Redstone.  For some other crushed ores, it became broken when Arch changed crushed from 2x to 2+n.

**Comment by Agrax** [comment]
Not really? Other ores still give the percentage when smelted, so the final amount is always 2 ingots x4. But redstone... is not smelted. So the multiplier is 1 ore->12 crushed-> 48 purified (other ores: 1 ore-> Y amount -> Y x 4 -> always ca. 8 ingots)

**Comment by pyure** [comment]
Its different by the end of processing because of byproducts.  Anything with a chanced output (which is everything) has more chances to trigger if there are more crushed ores coming in.

**Comment by pyure** [comment]
Changes submitted via PR

**Comment by pyure** [comment]
Done in infitech-prototype-0.44

**Comment by Agrax** [comment]
Not *quite* done. The bee version is fixed. But the bee+agri way still gives 6x instead of 3x (@Black0305 had to do it).
