### ISSUE TITLE
Plunger can't be used if less than 1B remaining

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#461]
The plunger only drains full buckets, and can't be used to empty leftover fluid.
![2019-04-07_00 04 34](https://user-images.githubusercontent.com/19927604/55675864-7e2c1600-58c9-11e9-8db0-051eecd91957.png)
Should this be changed? I thought this was the actual purpose of the plunger.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.45
