### ISSUE TITLE
No cutting machine recipe for rubber wood

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#462]
![2019-04-07_00 19 49](https://user-images.githubusercontent.com/19927604/55675973-1d054200-58cb-11e9-8a54-ec59bb1333bc.png)
I suppose this is a missing recipe, and not on purpose?

**Comment by pyure** [comment]
Missing.  I've added some other rubber stuff that wasn't covered, I'll add this too.

**Comment by Agrax** [comment]
#468 Fix is there. Somewhere

**Comment by Agrax** [comment]
#468

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.45
