### ISSUE TITLE
Sulfur dusts don't merge in inventory

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#463]
Different sulfur dusts don't merge, like ingots do for example.
![2019-04-07_00 25 21](https://user-images.githubusercontent.com/19927604/55676007-e54aca00-58cb-11e9-8f20-30815e0f54f9.png)
In this case, this is GTCE sulfur dust (from ore processing) and Thermal expansion sulfur (obtained on drops from zombie pigmen).
Both can be used interchangeably in recipes, so this is only a minor storage issue.

**Comment by pyure** [comment]
Do they merge when you pick them up?

**Comment by TLaviron** [comment]
No, they do not.
Throwing either stack from my inventory to the ground, and picking them up, keeps them in their original form.

**Comment by pyure** [comment]
Gotcha, we'll unify them then.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.47b
