### ISSUE TITLE
Menril berries as compost

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#469]
They're too buff. From one tree you get half a stack of berries and they're worth 140 compost

**Comment by McRayJason** [comment]
It is like 16 berries from a tree, not 32.. But still it is bit too much for how easy you can get them

**Comment by Agrax** [comment]
I mean... Even rotten flesh gives a fair bit of compost ;P 140mB as well

**Comment by Agrax** [comment]
i've found another way to abuse the methane chain btw.

Stock can be made of everything. It gives 110 mb of compost, but the recipe is:
pot+ anything = 3 x stock
That means that you can easily make 330 mB of compost out of just shrooms (they give 50mB themselves)

**Comment by pyure** [comment]
Reminder to self: we've written the override script, just need to inject it into gregtech.zs when we have a moment.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.45
