### ISSUE TITLE
[A] Thermal Foundation *badly* needs an update

### ISSUE THREAD

**Issue by thePalindrome** [pyure/infitech-prototype#480]
(Slightly edited:)
> Last time we updated it was 7 months ago. There was a lot of fixes since then. The issue itself consists of TF fluid and itemducts loosing connection with GT stuff they're plugged into.
> 
> https://imgur.com/a/zX7Ydbq
> 
> Updating the block USUALLY works (not always), but it's just an annoyance to go underground every now and then and do block updates so that ducts start to connect once again

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.47b
