### ISSUE TITLE
BuildCraft Pipe recipes more expensive in assembler

### ISSUE THREAD

**Issue by BorisMulder** [pyure/infitech-prototype#482]
![afbeelding](https://user-images.githubusercontent.com/4689209/56229790-01dcc400-607b-11e9-930f-0464219074d1.png)
![afbeelding](https://user-images.githubusercontent.com/4689209/56229816-15882a80-607b-11e9-878c-5d37cc0a7167.png)
At least make them cost the same. Or revert the yields since the second one is harder.

**Comment by pyure** [comment]
Agreed
