### ISSUE TITLE
Obsolete script part

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#487]
https://github.com/pyure/infitech-prototype/blob/f467253dd308050f00e9aa4dc2e8c7a068db7a15/scripts/gregtech.zs#L495

**Comment by pyure** [comment]
Looking into this.  Tangent: one of the other paper recipes appears to have an oredict typo.

**Comment by pyure** [comment]
Confirmed; I've deleted our versions of these recipes in dev.

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.47b
