### ISSUE TITLE
Batteries filling up beyond 100%

### ISSUE THREAD

**Issue by BorisMulder** [pyure/infitech-prototype#492]
Batteries are filling up to beyond 100% on 0.47:
https://cdn.discordapp.com/attachments/566722375257817098/571775326439604274/unknown.png

Also, the percentage bars are expanded as well:
https://cdn.discordapp.com/attachments/566722375257817098/571776574253301763/unknown.png

It also happens on other voltages (checked LV, MV and HV) and with different types of batteries:
https://cdn.discordapp.com/attachments/566722375257817098/571780559165194275/unknown.png

It happens on old servers being updated as well as newly created ones. The power in the batteries is real and can be used to power machines.

I don't know if this is a Gregtech or a Infitech issue.

**Comment by BorisMulder** [comment]
Right. I was just testing it on a non-infitech world with the same version of GT and can confirm it happens there too.

**Comment by pyure** [comment]
Thanks, smart check.

**Comment by pyure** [comment]
Fixed in 1.0.0
