### ISSUE TITLE
[Suggestion] Lubricant overhaul

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#501]
There's no incentive to find talc/soapstone. To remedy that i came up with a solution:
Step 1: make redstone veins a bit less abundant (they're literally everywhere now and they give retarded amounts of redstone)
Step 2: Make lubricant production via redstone less efficient (three recipes: seed oil, oil and creosote)

**Comment by BorisMulder** [comment]
You can also just make lubricant at 50% efficiency in the distillery. Creosote will be plenty anyway once you get some coke ovens running

**Comment by pyure** [comment]
I'm fine reducing the value of redstone in lubricant recipes.  I can make the redstone veins a bit smaller and very slightly more rare.  People currently hate finding redstone due to lack of surface rocks (although they're finding new tricks every day it seems)

**Comment by pyure** [comment]
Reducing lubricant efficiency seems good too.

**Comment by pyure** [comment]
Fixed in 1.0.0
