### ISSUE TITLE
[Bug] Railcraft steel tools

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#503]
Railcraft steel tools are not gregged, but they are pretty much the same as their TF counterparts. There's a whole set of tools in RC: hoe, shovel, sword, pickaxe, a whole set of steel armor and sheers. Additionally there's a whole set of crafting grid blocks: copper, tin, bronze, lead, silver, nickel, invar, invar, zinc, brass

**Comment by pyure** [comment]
All this stuff seems to be manageable from the RC config.
* disabled tools indicated above
* disabled armor
* disabled all metal blocks

**Comment by pyure** [comment]
Fixed in 1.0.0
