### ISSUE TITLE
[Bug] RC metal platforms

### ISSUE THREAD

**Issue by Agrax** [pyure/infitech-prototype#504]
RC metal platforms have recipes that use posts which are disabled. Either disable those as well or un-disable posts. Im fine either way. Just ne consistent with your choices

**Comment by pyure** [comment]
Not a choice, just one of millions of easily missed recipes.

**Comment by pyure** [comment]
I think these were victimized when the Rolling Machine got disabled.  There's probably more similar recipes.

**Comment by pyure** [comment]
added greggy recipe in dev

**Comment by pyure** [comment]
Fixed in 1.0.0
