### ISSUE TITLE
No recipe for air

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#505]
While looking into the processing chain for making nitric acid, I noticed that while you could get Nitrogen from air/liquid air, there are no recipes for making air (which is needed for liquid air, obviously), or at least none that appear in JEI. 
The infitech 2 method of putting empty cells in a compressor yields nothing.

Is this a design feature, making nitrogen a more difficult to obtain resource, or simply some missing functionality?

**Comment by Xavion3** [comment]
There should be a dedicated machine called an air collector I believe, it was a change by GTCE iirc.

**Comment by thePalindrome** [comment]
There's a gregtech machine called an "Air Collector", that produces Air at a steady rate (it's moderately low powered)

**Comment by TLaviron** [comment]
Thanks for the info.

Would it make sense to either add a recipe in JEI so it shows up when looking up air, or maybe add a related quest/task so we know to look for it?

I mean, it was two items away in JEI when searching 'air', but my tired eyes missed it among all the stairs...

**Comment by pyure** [comment]
Xavion added info in JEI in dev

**Comment by pyure** [comment]
Fixed in 1.0.0
