### ISSUE TITLE
Cannot craft Builcraft wrench

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#506]
Hello,

Due to buildcraft stonegear being deleted in infitech and no replacement exists from GT or other mods, it is not possible to craft Buildcraft wrench nor the marker connector. 
I'm trying to orient Builcraft pipes correctly, I don't know if I can use a different wrench for that, but GT ones don't work.

**Comment by pyure** [comment]
Thanks, will fix that recipe. In the meantime, I'm pretty sure I found a working wrench last week.  The crescent hammer maybe, or the ae2 wrench maybe.

**Comment by JoelLaviron** [comment]
Thanks, I will try the other wrenches.

**Comment by pyure** [comment]
Fixed in 1.0.0
