### ISSUE TITLE
[Bug] Advanced rocketry rolling machine produce buggy item with no input

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#508]
Hello,

I was using the rolling machine from advanced rocktetry to produce void metal plate (for golems), as there is no recipe with a GT bender (I don't know if it is a design choice or not).
I noticed that when supplied with water and power but no other items, the rolling machine was producing a buggy item with no name and no texture, and some kind purple rectangle as mouseover text.

I reproduced the bug in creative with a rolling machine with most basic motor and coils, creative power input, and some water in the tank.
It doesn't seem to prevent making the normal recipees though, I was able to make plates from ingots for instance. So it is quite annoying but not blocking.

**Comment by pyure** [comment]
Thanks JoelLaviron, will generate two tickets for this:
* Add Void Metal Plates to Bender
* Fix Rolling Machine broken no-input recipe

The latter is more-or-less temporary while we decide wtf to do with the Adv. Rocketry machines.

**Comment by pyure** [comment]
Fixed a bunch of rolling machine recipes, including the one you identified.
Added void metal plate recipe to bender.
(done in dev)

**Comment by JoelLaviron** [comment]
Nice, thanks

**Comment by pyure** [comment]
Fixed in 1.0.0
