### ISSUE TITLE
Aluminium items from Vulpes lib/Advanced Rocketry uncraftables

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#509]
Hello,

I  tried to make the aluminium sheets required to do the high pressure tanks for the silicon age quest 'Bring what you need' but even though the recipe accept any aluminium plate, it didn't work with GT plate. In fact it is because it is spelled 'aluminum' with the second 'i' in all of Vulpes library mod and Advanced Rocketry. Even if you somehow got hand of and Vulpes Aluminum plate, it is instantly converted in your inventory to a GT aluminium plate, so I guess this makes a lot of recipees incraftable.

I don't know what is the best solution:
-a workaround like for Thaumcraft plates needed for research, where you can convert one to the other (seems not very practical)
-Some way to make aluminium and aluminum related object equivalent in oredict? No idea if feasible.
-Use a script to rename all aluminum stuff from Vulpes/Advanced Rocketry to aluminium? As it seems unlikely the owners of these mods would rename everything on their side as it is working fine from their point of view.

**Comment by pyure** [comment]
I've added all of ore:plateAluminium to the ore:plateAluminum oredict, so that GT plates will qualify for any Adv Rocketry recipes that could be kicking around.  Thanks for the report as usual JoelLaviron.

**Comment by pyure** [comment]
Fixed in 1.0.0
