### ISSUE TITLE
Bioplastic (NuclearCraft) is uncraftable

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#511]
Hello,

Bioplastic item from NuclearCraft is uncraftable, but is used for some recipees like medium radiation shielding, Hazmat suit.

**Comment by pyure** [comment]
97% fixed in dev.  Apparently its used as well for a filled Radaway cannister.  I've created a separate issue to attend to that.  

In the meantime, all recipes that used bioplastic will instead use polyethylene.

**Comment by pyure** [comment]
Fixed in 1.0.0
