### ISSUE TITLE
[Quests] All quests requiring fluids are consuming the fluid

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#513]
Hello,

We noticed that all quests requiring fluids consume the fluid, while we would expect to consume only for repeatable quests? It's a bit annoying to lose the fluid when doing quests like light/heavy fuels quests, plastic quests, rocket fuel quests.

**Comment by pyure** [comment]
Certainly agree, will look into it.

**Comment by pyure** [comment]
This may be a limitation of the tech.  I'll check with the dev, but worst case scenario, I'll ensure the fluid quests give you back >= same fluid back in kind.

**Comment by pyure** [comment]
Joel, I did more or less give-you-fluid-back scenario above.  In some cases (such as rocket fuel) where I'm trying to walk the user through a many-step chemistry process, I don't give back the fluids at each step, but instead give a larger amount for the finished product.  (This strategy would only be super applicable where those preliminary fluids don't have obvious alternative uses at that stage of the game)

**Comment by pyure** [comment]
Fixed in 1.0.0
