### ISSUE TITLE
Reorder Silicon quests

### ISSUE THREAD

**Issue by BorisMulder** [pyure/infitech-prototype#518]
The silicon questline has one part which is a bit weird imho. 

The part where you require oil -> distillery -> polyethene -> adv. assembler is not needed in order to craft basic/good circuits in the assembler. In fact, it is more efficient to do the latter first as it gives discount on the many circuits you need to craft the advanced distrillery, chemical reactor and assemblers needed for the quests prior to it.

These prerequisites seem to be intended for the quest to produce advanced circuits, but the one that requires the silicon boule, the one with the advanced engraver/cutting machine and ICs should come before the oil quest even. Maybe make it a two fold path with one leading to plastics and oil processing and another leading to silicon, which at the end are both required for the advanced circuit?

This also comes back to my remark I made some time that the quest to make basic circuits comes right after the one to make the first hand-crafted good circuit. You need silicon for that one.

Besides, you cannot craft polyethylene with oil early game as that requires a HV cracking unit so you need to go the ethanol way. Therefore I reccomend making the "black gold" quest optional as well and move it into the fuel tree.

So here is how it should look like if you ask me:
```
           /  => oil => (optional diesel tree)
good circuit  => silicon boule => adv. engraver => adv. cutting machine => basic+good circuit =========> Advanced circuit
           \  => polyethylene => adv. assembler => (rest of tree required to make advanced circuits) =/
```

**Comment by pyure** [comment]
Great feedback, thanks.  I'll admit I'm a bit caught offguard by the ethanol suggestion.  In previous iterations it was normal to go the oil route.

**Comment by BorisMulder** [comment]
I think this ethanol part should either be changed to allow to make ethylene from oil products, or that this quest line is a bit extended to include the complicated ethanol + sulfuric acid -> ethylene process which requires an advanced reactor and a still and can be further tweaked by an advanced distillery instead of the still.

**Comment by BorisMulder** [comment]
Notice that the next tier, to make nano processors, also requires a seed oil farm. In the quests the fact is reflected that you need epoxy resin and epichlorohydrin to make nanoprocessors. However, epichlorohydrin requires either Allyl Chloride, which in turn requires propene and therefore cracking (which requires nanoprocessors to begin with), or glycerol, which is a byproduct of making bio diesel with seed oil.
Again, I dont know if this is a feature, but it seems to me that large setups are needed to progress through the quests, though there are no quests to guide you through the setup itself.

**Comment by pyure** [comment]
Yeah, the major problem is that there's so many ways to get this stuff a lot of the time.  I don't want to suggest that players make a Still if they'd prefer the Advanced Distillery route.

My understanding above is that there's a logical chokepoint (glycerol) which I can add. I can't recommend Allyl Chloride at this point because we cannot crack fluids yet.

I can add Allyl Chloride to the task list to make that a bit simpler.  

Any other suggestions that reflect obvious chokepoints that everyone needs to go through?

**Comment by BorisMulder** [comment]
Ehh, the quests after the HV assembler quests all still consume fluids but dont reward them. I saw you fixed that for the earlier quests, but not for the last ones.

**Comment by pyure** [comment]
Which ones?  There's a couple cases where I delay the reward until you reach a final-product quest.

**Comment by BorisMulder** [comment]
I edited my post

**Comment by pyure** [comment]
I literally just closed my instance.  Can you please recommend reward for the first, and consumption amount for the latter?

**Comment by BorisMulder** [comment]
The Polyvinylchlorid quest costs 1B Ethylene +2B cholrine which makes 1B vinyl chloride + 1b vinyl chlorde = 2B VC. This makes 3B PVC with a lot of oxygen which I assume is free (since you will get it from many electrolyzer recipes). You need an additional 1B PVC so the total cost is 4B PVC

 + 1B oxygen which is good for 216 mB PVC. From this, 144 is used to make the foils for the next quest. The next quest gives 16 capacitors which equals 1 aluminium foil + 4 PVC foils.
The expensive part is the effective 4B PVC required to complete the quest. So I suggest you just reward at least 4 PVC cells in the PVC quest.

For the second quest, it is kind of hard as you either need 1B or 144mB epichlorohydrin to make an amount of epoxy resin. But since it is kind of hard to grant 144mB except by giving the resin sheets (which are in the next quest) I suggest you change this quest to require 1B of ECH, remove the naphtha and NO2 requirement completely, and instead add the requirement of 1B Glycerol and 1B HCl. Then it should reward 2B of epichlorohydrin or these rewards should continue to the next quest. It will look like this: 1B Hcl + 1B Glycerol + 1B ECH => gold + 2 ECH

**Comment by pyure** [comment]
BorisMulder, you on our Discord by any chance?  It would be handy to be able to debate ideas in real time occassionally :)

**Comment by pyure** [comment]
Regarding the first conversation (Oil and Polyethylene), I'll make the following changes:
* Change distillery to require MV (not LV or MV.  You need MV to get polyethylene via the ethanol route)
* Make "Black Gold" (get Oil), and "Pump up the Jam" (make a pump) OPTIONAL quests branching from "Distillation"
* Add a new required quest (called "Plastic Precusor") after "Distillation" and before "Plastic" which breaks down the requirements for Ethylene.
* Add a new required quest after "Plastic Precursor" that requires a MV Chemical Reactor (since its critical to proceed)

**Comment by pyure** [comment]
* PVC quest now gives 4 cells of PVC as a reward
* Replaced Naphtha and NO2 with Glycerol and HCl respectively
* Glycerol + HCl + Epichlorohydrin quest now gives 2 cells of ECH as a reward

**Comment by BorisMulder** [comment]
> 
> 
> BorisMulder, you on our Discord by any chance? It would be handy to be able to debate ideas in real time occassionally :)

Oh sorry, haven't said that, I'm Altadoon on discord

Looks good for the rest :)
