### ISSUE TITLE
Missing image on title screen on linux.

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#519]
![2019-05-09_22 46 20](https://user-images.githubusercontent.com/19927604/57485696-b9e14380-72ac-11e9-889b-9fcabdc174f2.png)
Out of 3 people on our server, the 2 playing on linux have this placeholder image on the title screen, while the other one (on windows) has the intended image shown (the infitech 3 stylized text, I believe).
Perhaps there is an issue with '/' and '\\' in filepaths, or something similar.

**Comment by pyure** [comment]
That means I botched the casing more than likely.  I use windows, which is case-noobish.

**Comment by pyure** [comment]
I've made everything lower-case, hopefully addresses the issue.
