### ISSUE TITLE
Quest for Advanced Laser Engraver only accepting Green Sapphire Lens

### ISSUE THREAD

**Issue by BorisMulder** [pyure/infitech-prototype#522]
![afbeelding](https://user-images.githubusercontent.com/4689209/57583851-1d4dba00-74d5-11e9-88c9-5c7cedd325b8.png)

Something went wrong with the ore dictionary there.

Since green lenses are not needed at this point in the game, but red and white are, it would be nice to actually accept them in this quest.

**Comment by pyure** [comment]
Boris, you didn't really explain if something's broken here. At the time this quest was assembled, there was only one type of Green lens, so I didn't need to use an ore dictionary.  The other types needed it.  Is there actually something broken here?

**Comment by BorisMulder** [comment]
Well, I mean that it won't accept any kind of red or white lens at all, only the green one. It implies it should also accept any red or white one.

**Comment by pyure** [comment]
Woops, glad you clarified, I actually thought you meant the green was failing.

Will definitely investigate.

**Comment by pyure** [comment]
Oredict filter wasn't behaving.  I've added the various lenses in manually.  May have missed one or two due to colourblindness :p
