### ISSUE TITLE
Crash with unusual torch placement

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#523]
Hello, 
I have experienced a server crash, that seems to have occurred when a torch was placed when it shouldn't have.

I was trying to access a machine inventory. I was holding torches in my hand. 
After right clicking, since the UI took some time opening, A torch was placed on the front of the machine I was pointing at. I've seen this happen a few times, I think.

However in this case, there was already a block in front of the machine in question, specifically a polyethylene pipe draining the machine (which had a pump+filter on its side).
So, the torch tried to replace a pipe (or actually replaced it), and the server crashed right after that.
I am not entirely certain this is what actually happened, but its what I could see before getting disconnected.

Save is corrupted, had to restore a backup. I have attached a crash log.
[crash-2019-05-12_18.42.12-server.txt](https://github.com/pyure/infitech-prototype/files/3170342/crash-2019-05-12_18.42.12-server.txt)
I can also provide a log from the debug output, it may provide additional useful information.
[server_debug.log](https://github.com/pyure/infitech-prototype/files/3170345/server_debug.log)

**Comment by TLaviron** [comment]
Update: this is reproducible on a simple setup
![2019-05-15_19 24 45](https://user-images.githubusercontent.com/19927604/57796723-19c26900-7749-11e9-84aa-7d46d0e80e16.png)

For the exact setup, that's an electrolyzer MV, with a pump + fluid filter filtering oxygen, pumping into a 2-bloc polyethylene tiny pipe, and emptying into a quantum tank LV.
Shift-right clicking to force a torch placement on the side with the covers causes a crash.

I would guess that the actual machine types or pipe types don't matter, but I have not yet tested again with different setups (It requires relaunching the client each time if testing in singleplayer).

**Comment by pyure** [comment]
Hey TLaviron, I believe this is a known issue.
https://github.com/TheCBProject/ForgeMultipart/issues/56

I check up on it from time to time to see if there's any progress.

**Comment by pyure** [comment]
Its been a long time coming, but I think this is fixed by the mod dev.  I need to do a bit more testing, but should roll out with next version.

**Comment by pyure** [comment]
Fixed in 1.09
