### ISSUE TITLE
Cannot make diamond from dust in implosion compressor

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#524]
Hello, 
contrary to the other gems, diamond the recipe to make diamond from diamond dust in the imposion compressor is missing.
Currently, the only way to get back diamond from the dust is explosion crafting which is not very practical.

**Comment by Agrax** [comment]
Known issue. 99% sure that it’s GTCE-side

**Comment by JoelLaviron** [comment]
Yeah most likely. But since I found the issue in infitech3 and did not check with GTCE only, I prefer to raise the issue here first. I did not find any issue (open or closed) on GTCE though.

**Comment by pyure** [comment]
Archengius is definitely aware of this; I have no idea if he plans to fix it on his side, and its trivial to add a stand-in recipe for it our side.  Done in dev.

**Comment by Agrax** [comment]
Yes, he plans to do that, but i wouldn’t count on Arch releasing anything for tye next two weeks
