### ISSUE TITLE
Cannot craft Upgrade Frame (GenDustry)

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#525]
Hello,

Even though the recipe is present in JEI and accept aluminium ingot, I cannot craft it on a workbench. I can transfer the required ingredients to the workbench with JEI, so from JEI point of view my ingredients match the recipe but then I cannot craft it.

**Comment by Agrax** [comment]
https://github.com/pyure/infitech-prototype/blob/1ece7d0001a63986aabdf5b8acd823a9066cff63/scripts/gendustry.zs#L40

I can safely assume it’s an oredic error. CT doesn’t throw oredic errors. Show us an img with the recipe from JEI, please

**Comment by JoelLaviron** [comment]
Recipe from JEI, accepting any redstone block and both aluminium and aluminum ingots:
![JEI_upgrade_frame_recipe](https://user-images.githubusercontent.com/26551406/57983281-467bc680-7a50-11e9-8456-7961160a9180.png)
My tentative of crafting: standard minecraft redstone block, GTCE aluminium ingots:
![craft_upgrade_frame_not_working](https://user-images.githubusercontent.com/26551406/57983323-9b1f4180-7a50-11e9-94cc-650f89d3e26f.png)

**Comment by Agrax** [comment]
Yup. An oredic issue. There should be a cobalt frame inside, which apparently doesn’t exist anymore

**Comment by JoelLaviron** [comment]
Ok. Thanks for the help Agrax

**Comment by pyure** [comment]
Recipe references an item which doesn't exist.  Not sure what the original intent was; I've removed the center ingredient.

**Comment by Agrax** [comment]
Don’t you remember the GT update that removed most frames? Don’t remove the frame, just change it for another. Dunno, an iron one

**Comment by pyure** [comment]
The vanilla recipe doesn't call for a center ingredient, and a iron frame just adds busy-work needlessly.  I'm fine with it as is (until I play some Gendustry maybe)

**Comment by Agrax** [comment]
You usually don’t :P Just FYI: it2 introduced a frame in the middle. Imho it’s a nice idea, coz alu plates have to stick to „something”, aight?
