### ISSUE TITLE
Can't craft nether quartz plates

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#529]
Hello,

Because of conflicting recipes, the nether quartz plate can't be crafted (required for ME terminals)
![2019-05-26_20 25 25](https://user-images.githubusercontent.com/19927604/58385721-0b036e00-7ff5-11e9-8ae5-4114956adefa.png)
The quartz block -> quartz slab recipe in the cutting saw prevents the plate recipe from being made.

I would suggest disabling the slab recipes, since there is an equivalent manual recipe.

**Comment by pyure** [comment]
I did indeed remove the slab version.  Also mentioned it to GT-CE, this is an issue on their side.

https://github.com/GregTechCE/GregTech/issues/848
