### ISSUE TITLE
No recipe for GT electric screwdriver

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#530]
Hello,

I noticed that there is no recipe for the LV screwdriver, while there are for every other electric tool.

**Comment by pyure** [comment]
Confirmed, and weird.  Hard to believe that could be a GT bug but we're not (deliberately) removing the recipe.  Will fix.

**Comment by pyure** [comment]
Confirmed its a GT issue; I'm not sure how to add a generic recipe to handle material variants so I need to leave this with Arch.

**Comment by pyure** [comment]
https://github.com/GregTechCE/GregTech/issues/847
