### ISSUE TITLE
No Recycling recipe for Arsenic Trioxide dust

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#531]
Hello,

I was in the process of making blue alloy, and the recipe for cobalt oxide dust creates some arsenic trioxide as byproduct (As2O3). There is no electrolyzer recipe (or other) to turn it into its base components, so it currently cannot be recycled (which is not a big deal, but it takes some storage space).

**Comment by pyure** [comment]
I have no idea if its realistic to be able to electrolyze As2O3 into its constituents but I'll add that anyway.
