### ISSUE TITLE
disable AR chemical reactor

### ISSUE THREAD

**Issue by BorisMulder** [pyure/infitech-prototype#535]
currently it has one usage showin in NEI:
![afbeelding](https://user-images.githubusercontent.com/4689209/59132840-86aad680-8976-11e9-9679-91c8452fc417.png)
looks like its producing charcoal at the cost of 800RF (aka. free)

**Comment by pyure** [comment]
Yeah that's definitely a bit silly.  Can you think of any way we could keep the chemical reactor?  I hate disabling machines if I can help it.  What if it were gated really late and gave some slightly friendlier versions of some recipes?
