### ISSUE TITLE
Server crash with new gregtech cover behavior

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#537]
Hello, 

Just upgraded from 1.0.3 to 1.0.4 
The server crashed shortly after starting with a 'NoSuchMethodError' exception (crash log attached
[crash-2019-06-22_16.00.43-server.txt](https://github.com/pyure/infitech-prototype/files/3316911/crash-2019-06-22_16.00.43-server.txt)

Also, before crashing, the log was filled with messages similar to the following
[16:00:43] [Server thread/INFO] [STDOUT]: [gregtech.api.capability.impl.EnergyContainerBatteryBuffer:acceptEnergyFromNetwork:31]: south 31 1 BlockPos{x=-140, y=63, z=876}
This is probably unrelated but it does spam the console log

With a second attempt, I was able to connect before the server crashed (which happened a few seconds afterward).
The stack trace seems to indicate that thaumcraft golems are involved, supposedly when interacting in some way with gregtech storage blocks.

**Comment by TLaviron** [comment]
I saw there was a hotfix for GTCE (gregtech-1.12.2-1.8.3.418.jar), which does address the leftover log, and some other fixes but sadly this did not improve this issue.

**Comment by pyure** [comment]
https://github.com/GregTechCE/GregTech/issues/868

**Comment by pyure** [comment]
Will keep an eye on it.  Will also roll back IT3 to .399 which is a bit more stable apparently.

**Comment by pyure** [comment]
Fixed in last IT version I believe, neglected to close it here.

Worth mentioning that I don't think the GT covers mechanics are totally solid yet.
