### ISSUE TITLE
Some recipes require IV or higher, but the machine for it does not exist

### ISSUE THREAD

**Issue by BorisMulder** [pyure/infitech-prototype#538]
Uranium oxide:
![afbeelding](https://user-images.githubusercontent.com/4689209/60130258-336abd80-9797-11e9-823c-1e3113256914.png)

A lot of things related to SoCs:
![afbeelding](https://user-images.githubusercontent.com/4689209/60130312-4b424180-9797-11e9-9129-4bdd74d1c800.png)
![afbeelding](https://user-images.githubusercontent.com/4689209/60130370-62812f00-9797-11e9-952a-dfb6dad645c5.png)
![afbeelding](https://user-images.githubusercontent.com/4689209/60130403-6f058780-9797-11e9-85c3-e989d870c422.png)
![afbeelding](https://user-images.githubusercontent.com/4689209/60130478-92c8cd80-9797-11e9-91df-dcb40c61cf89.png)

**Comment by pyure** [comment]
Removed the Uranium processing ones.  The others I think are just GT quirks.
Addressed in 1.0.5
