### ISSUE TITLE
Quest pyure

### ISSUE THREAD

**Issue by McRayJason** [pyure/infitech-prototype#547]
Hey. Just a small one.
Quest Pyure wants cleaned iron dust, but quest before to crush the ore wants anything that yields iron (for example limonite) I think the Pyure quests should also look for any iron yielding dust.
V1. 0.6b

**Comment by pyure** [comment]
In theory "Pyure" was supposed to be a silly joke but also a requirement: get "pure" iron (which you can theoretically do by mortaring an ingot iirc)

That said, if ppl think it feels off, we'll tweak it.  Will think about it.

**Comment by pyure** [comment]
Added Limonites + Banded Iron for now.  I don't feel good about Magnetite.  And I'm probably just straight up forgetting some.
