### ISSUE TITLE
AE2 craft tweaker issues

### ISSUE THREAD

**Issue by karikamiya** [pyure/infitech-prototype#555]
A few quick recipe things:

Fluid interface maybe not changed from default.
Crafting Unit might require 3 processors instead of 2 proc and 1 circuit.

I'm on 1.0.6b

**Comment by karikamiya** [comment]
It appears there are many different places the calc proc needs to be instead of the calc circ. If this is not intended i can fix

**Comment by pyure** [comment]
I'm not at home right so I cannot confirm, but I think the fluid interface recipe was just an extension of the interface recipe, which did have a changed recipe from default. (If that's correct, the fluid interface is fine as is )

I'm not sure what you're suggesting regarding the Crafting Unit.  What's wrong with the current recipe?

I agree that there are problems with the calculation processor recipes; it looks like an error when we ported over from IT2.  If you want to list the recipe, or pull request a fix, I would be pleased to review and merge it.

**Comment by pyure** [comment]
I'll close when its released, thanks tho mike :)

**Comment by karikamiya** [comment]
ah, k. cheers
