### ISSUE TITLE
GTCE chests are useless due to Iron Chests

### ISSUE THREAD

**Issue by Divran** [pyure/infitech-prototype#57]
GTCE chests (titanium, tungstensteel, etc) are way more expensive and smaller than chests from the Iron Chests mod, making them useless, some balancing required

**Comment by pyure** [comment]
I'd like to hear suggestions on this one.  I agree this is an issue.

**Comment by Agrax** [comment]
i've got only one idea. get gid of GT chests

**Comment by pyure** [comment]
Its definitely an option

**Comment by Agrax** [comment]
GregTechCE/GregTech#527

Just for the reference

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.39.1
