### ISSUE TITLE
Calcium sulfate (dust) from NuclearCraft is impossible to craft

### ISSUE THREAD

**Issue by JoelLaviron** [pyure/infitech-prototype#570]
Currently you can only obtain it from 'Calcium Sulfate Solution' which is only obtainable from 'Calcium Sulfate' dust.
This makes it impossible to create 'Crystal binder' required for Elite Plating (Tier 4 NuclearCraft).
I have no idea what was the original way to obtain it in NuclearCraft though.

**Comment by ct-klein** [comment]
Ticket has already been written up and it's being looked into.  Thanks :)

**Comment by pyure** [comment]
hmm I see it in the Crystallizer machine, I wonder if this is already fixed in dev
