### ISSUE TITLE
Star tank from FluidTanks is not craftable

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#578]
Hello, 

There is a recipe for crafting the star tank that is shown in JEI, but matching the recipe in any crafting grid does not produce any output.

![2019-10-13_15 18 35](https://user-images.githubusercontent.com/19927604/66716452-14d41500-edce-11e9-9529-b7c4530f0fef.png)

Based on the name and the recipe pattern for the other tiers, it seems there should be 2 nether star plates on the empty holes (the fact that there is a config entry in the fluidtank.cfg for the star tank material also points in this direction).

Adding nether stars or nether star plates in the empty slots does not produce anything new.

**Comment by pyure** [comment]
Thanks for the PR on this deanorhan.  Fix is live in v1.12
