### ISSUE TITLE
Mitts don't protect from hot ingot damage

### ISSUE THREAD

**Issue by TLaviron** [pyure/infitech-prototype#579]
Carrying any kind of hot ingot still deals damage even when wearing the mitts in the offhand.

The mitts still protect against carrying containers of hot fluid (e.g. a bucket of lava).

**Comment by ct-klein** [comment]
Arch has stated that the hot ingots will not be affected by the mitts mod.  Shouldn’t be carrying molten ingots or some such.  IT3 can’t affect that.

**Comment by TLaviron** [comment]
Ok, thanks for the info, I guess it makes sense that oven mitts shouldn't protect against molten metal.

I can close the issue then.
