### ISSUE TITLE
there are too many bronze dust recipes

### ISSUE THREAD

**Issue by Divran** [pyure/infitech-prototype#58]
Basically every mod adds its own bronze dust recipe, and any recipe that results in bronze ingots that aren't  from GTCE will not complete the bronze ingot quest near the bottom of the questbook.

For example, 3 copper + 1 tin = 3 bronze blend from thermal expansion. Smelt these and you get TE bronze ingots. I'm sure there are more but I'm getting the TE recipe crash issue a lot so I can't check right now.

**Comment by Agrax** [comment]
I’ve already fixed it. The fix will be in the next version

**Comment by pyure** [comment]
@Agrax can you remind me what the status of this is?

**Comment by Agrax** [comment]
I added oredic to the quest, so that any bronze blend triggers this quest to complete

**Comment by pyure** [comment]
@Divran this fixes the quest doesn't directly address "too many bronze dust recipes."  Is the "too many" still a major problem or can we close this?

**Comment by Divran** [comment]
In IT2 the normal crafting table recipes for bronze dust were much worse than using machines to do it, on purpose, so that you get an upgrade once you make your first steam machines. Most likely, there's still many recipes for bronze that are as good as using machines, so those will have to be removed or edited if you want the same thing in IT3.

**Comment by Agrax** [comment]
For example? We don’t want the same thing. We want a better thing

**Comment by pyure** [comment]
I did disable shapeless recipes from giving 4 bronze.  If you find any more please reopen ticket.
