### ISSUE TITLE
Bad recipe of Black Elevator from OB

### ISSUE THREAD

**Issue by danirpg** [pyure/infitech-prototype#583]
The recipe of black elevator from OB doesn´t match the difficulty of recipe than the other colored elevator, making this elevator easy to craft at early ages.
![Captura](https://user-images.githubusercontent.com/15187376/72425252-b67d5080-3787-11ea-8436-e1e4c0b3fc69.JPG)

**Comment by pyure** [comment]
Thanks for the PR on this deanorhan.  Fix is live (v1.12)
