### ISSUE TITLE
Deep Resonance Purifier Uncraftable

### ISSUE THREAD

**Issue by winsomniak** [pyure/infitech-prototype#584]
For some reason, I can't craft this machine all components correctly placed in the crafting grid. 

<img width="1680" alt="Screen Shot 2020-01-17 at 01 07 00" src="https://user-images.githubusercontent.com/11396781/72546437-bbe0b500-38c5-11ea-932e-4b140c3ab851.png">

**Comment by deanorhan** [comment]
Not sure what item it was supposed to be, but the recipe calls for a <ore:craftingFilter>. And there is no oredict with that name.

**Comment by pyure** [comment]
Yikes, thanks for the info, will fix.

**Comment by pyure** [comment]
GT must have removed that oredict.  Fixed in dev, will be in next release.
