### ISSUE TITLE
Planet Id Chip requires the wrong tin

### ISSUE THREAD

**Issue by BorisMulder** [pyure/infitech-prototype#588]
I also noticed a mistake: for the Planet Id Chip, you can make it using tin or solder. but the Tin one requires Foundry Liquid Tin, which is unobtainable. It should be changed to require GT liquid tin.

~Boris (AKA Altadoon)

**Comment by BorisMulder** [comment]
Same for the Planet Id Chip

**Comment by pyure** [comment]
Thanks, fixed in dev
