### ISSUE TITLE
Bronze in Alloying Crucible

### ISSUE THREAD

**Issue by Black0305** [pyure/infitech-prototype#594]
Jason mentioned it on the stream. Our quest says:
![alloy](https://user-images.githubusercontent.com/42079463/81446041-5ec18580-917a-11ea-9b98-77fe0fb49d46.PNG)

But our recipe is 4 copper + 1 tin = 4 bronze
https://github.com/pyure/infitech-prototype/blob/1e0950b589708ec873851969af568c9d51ebf159/scripts/foundry.zs#L532

**Comment by TedKnudsen** [comment]
Yikes.  Math is hard.

**Comment by Black0305** [comment]
#595 fixed
