### ISSUE TITLE
VERY low fps (2-3 with lowest settings)

### ISSUE THREAD

**Issue by DNVIC** [pyure/infitech-prototype#605]
I just installed the pack because I enjoy similar packs. Unfortunately, I seem to be unable to play due to the very low fps. I'm using 6gb of ram which is usually enough for most packs, and I dont think throwing more ram is the solution

Specs:
64-bit windows 10 operating system
AMD Ryzen 5 2600 Six-Core Processor (3.85 GHz)
16 gb Corsair Vengeance RAM (2x8gb)
AMD Radeon RX 580 GPU
MSI B450 Tomahawk

This is right when I load up a world so it cannot be due to a huge factory or something.

EDIT: Log is here: https://paste.ee/p/nR0uq
Interestingly, it is still in low fps even in the settings menu (once I load up the world). The only place where it is not in low fps is in the title screen

**Comment by Black0305** [comment]
Try changing your MipMaps levels in video settings to 0. Had some friends with AMD graphic cards and those had the same problem.

**Comment by DNVIC** [comment]
Thanks, that fixed it!
