### ISSUE TITLE
Gregtech Gathering tools 

### ISSUE THREAD

**Issue by Sandrox1099** [pyure/infitech-prototype#64]
All gregtech tools can be used to scoop, harvest stone and ore. Normaly incorrect tools do not lose durability, but will harvest the block with correct drops.
![scoop noob](https://user-images.githubusercontent.com/24881685/44307343-fed0ed00-a3a0-11e8-8537-da0e2796bc43.PNG)
![shovel pick](https://user-images.githubusercontent.com/24881685/44307345-01cbdd80-a3a1-11e8-9d02-043e76ba0e76.PNG)

**Comment by Agrax** [comment]
It's a GT issue. Waiting for the fix

**Comment by pyure** [comment]
This is sort-of-fixed.  I still see a TOP checkmark when I try to harvest dirt with pickaxe or tree with shovel, but I do not gain tool-speed bonuses for them.  I get both an X and terrible speed if I try to mine Stone with a shovel.

infitech-prototype-0.15.zip
