### ISSUE TITLE
Iron ingots do not work with gregtech recipes

### ISSUE THREAD

**Issue by Sandrox1099** [pyure/infitech-prototype#65]
![metall plates](https://user-images.githubusercontent.com/24881685/44307381-afd78780-a3a1-11e8-9df4-4b207f50edc6.PNG)
All other gregtech recipes with iron ingots do not work as well.
The iron ingot are minecraft:iron_ingot

**Comment by Black0305** [comment]
All those recipes worked in version 0.12

**Comment by pyure** [comment]
It seems to be GT-specific.  Our tests removing scripts only "worked" because the problem itself is erratic.  I've reproduced the problem with nothing but GT, JEI and CodeChickenLib installed.

https://github.com/pyure/infitech-prototype/issues/65

**Comment by pyure** [comment]
Fixed by GT.  Available in infitech-prototype-0.15.zip
