### ISSUE TITLE
EnvironmentalTech solar arrays need to be nerfed into the ground or disabled

### ISSUE THREAD

**Issue by Divran** [pyure/infitech-prototype#74]
this handy table https://ftb.gamepedia.com/Solar_Array_Controller tells you how much power each tier+solar panel combination produces

**Comment by pyure** [comment]
Agreed.  We'll make plans once we're tackling the relevant game stage.

**Comment by pyure** [comment]
We're yanking this mod from the pack so no longer relevant.
