### ISSUE TITLE
Bronze wrench durability

### ISSUE THREAD

**Issue by Sandrox1099** [pyure/infitech-prototype#75]
A bronze wrench only has a durability of 1920. 
-> You just can change the direction a machine is facing 3 times

**Comment by TedKnudsen** [comment]
Thanks Sandro.  Known issue with item durability fwiw, same as the Flint Hoe problem.

Going to leave this issue opened until GT item durability as a whole is addressed.

**Comment by pyure** [comment]
Thanks Sandro. Known issue with item durability fwiw, same as the Flint Hoe problem.

Going to leave this issue opened until GT item durability as a whole is addressed.

**Comment by pyure** [comment]
GT addressed some durability issues recently. Is this still an issue?

**Comment by pyure** [comment]
Yes its still an issue.  Added a task on their side.

https://github.com/GregTechCE/GregTech/issues/324

**Comment by Rongmario** [comment]
Why are you speaking to yourself pyure

**Comment by pyure** [comment]
Ironically I knew you were gonna chime in, but I expected you to do it on 324, not 75 :p

**Comment by Rongmario** [comment]
BS

**Comment by pyure** [comment]
infitech-prototype-0.22.zip
