### ISSUE TITLE
Quest #106 Steam cooker misses its condition

### ISSUE THREAD

**Issue by Sandrox1099** [pyure/infitech-prototype#76]
![steam cooker](https://user-images.githubusercontent.com/24881685/44360522-5f544d00-a4bb-11e8-9815-38af6176549a.PNG)

**Comment by Agrax** [comment]
That's 100% my fault :P Fixing it now. Ty for the feedback

**Comment by pyure** [comment]
Fixed in infitech-prototype-0.15.zip
