### ISSUE TITLE
Drill Grinder crafting recipe makes no sense

### ISSUE THREAD

**Issue by Sandrox1099** [pyure/infitech-prototype#79]
![drill grinder](https://user-images.githubusercontent.com/24881685/44368907-b1ee3300-a4d4-11e8-8024-c2d5fca40d45.PNG)
This is the crafting recipe for the Drill Grinder, but in order to use it you have to put a second drillbit and advanced motor in its interface
![drill grinder interface](https://user-images.githubusercontent.com/24881685/44368955-e366fe80-a4d4-11e8-90c3-9b545f1e6330.PNG)
I would give the player a Drillbit and an advanced motor as a quest reward, because you already built the required parts into the machine.

**Comment by Agrax** [comment]
It’s a) default recipe
B) those parts break either way so we encourage to make multiple ones

**Comment by pyure** [comment]
@Sandrox1099 I'm inclined to agree with Agrax on this one (Although I'm pretty sure I did screw up some non-default FT recipes).

The way this mod works, you constantly feed it replacement parts  (and lots of them).  They don't require energy (weirdly) but do require bits, and motors and such.

Please re-open the issue if I'm being blind to something here.
