### ISSUE TITLE
Quest #87 So ironic misses its condition

### ISSUE THREAD

**Issue by Sandrox1099** [pyure/infitech-prototype#80]
![so ironic](https://user-images.githubusercontent.com/24881685/44369095-756f0700-a4d5-11e8-9b82-b9f80612449e.PNG)

**Comment by Agrax** [comment]
Another task missing? Pyure must’ve done smth with the quests accidentally

**Comment by pyure** [comment]
I looked through the git history for this quest and I cannot find any commits that include tasks for it.

Creating a work task for it.
