### ISSUE TITLE
GT Tank shows no content after breaking

### ISSUE THREAD

**Issue by Black0305** [pyure/infitech-prototype#88]
![tank1](https://user-images.githubusercontent.com/42079463/44754243-5c8fd280-ab21-11e8-9b77-a4b3c4dab5ff.JPG)
![tank2](https://user-images.githubusercontent.com/42079463/44754244-5c8fd280-ab21-11e8-8d94-033e56acc27a.JPG)

After breaking a Tank and placing it again, the liquid is still there but wont be displayed.
Should be a GT issue. Tested it on clean GT instance.

**Comment by pyure** [comment]
Fix released in infitech-prototype-0.16.zip
