### ISSUE TITLE
Thermal Foundation Gears

### ISSUE THREAD

**Issue by Black0305** [pyure/infitech-prototype#91]
You can craft them in the Foundry Metal Caster for only 4 Ingots. GT counterparts require 8 Ingots befor LV.

**Comment by Agrax** [comment]
I see... That needs tweaking,
@pyure we can either disable the gear mold alltogather OR make it use twice the amount of metal and produce GT gears. Or smth

**Comment by Black0305** [comment]
All recipes in the Metal Caster use less metal than the "GT Way" would do. Maybe disable metal caster and only use the casting tables?

**Comment by Agrax** [comment]
we can tweak everything. I think, at least

**Comment by Black0305** [comment]
Damn, plate casting table also uses only 1 ingot per plate.

**Comment by Agrax** [comment]
The MP is still in alpha state. We're doing our best. If you ever wanted to help, you can PR:

https://github.com/pyure/infitech-prototype/blob/master/scripts/foundry.zs

and here's the CT support:
https://github.com/Shadows-of-Fire/Foundry/wiki/Crafttweaker-Support

**Comment by Black0305** [comment]
I would disable the Metal Caster and tweak the Casting Tables to require double the amount of metal. If you´re find with that, i´ll do it. If you have other plans, tell me and i´ll try it too :)

**Comment by Agrax** [comment]
we should wait for pyure's decision. Im a simple Joe-Fix-It here xD

**Comment by TedKnudsen** [comment]
I think the metal caster is the one I put a lot of script-work into to provide interesting ingot recipes.  I'm super hesitant to disable it entirely.  That said, we can disable specific molds if necessary.

I'm fine with the caster making gears cheaper than 8 ingots and more expensive than 4 ingots.  (Say, 6 ingots).  Ditto with the casting tables.  

Black, if you're interested in helping with that, that's awesome.  If not let me know and I'll create a task for it internally and take care of it myself soon (tm)

**Comment by Agrax** [comment]
@Black0305 I think it could look like that:
Gears: 6 (maybe even 6,5) ingots
Plates: 2 (1,5? That could work. Whaddya think, pyure?) ingots

**Comment by Black0305** [comment]
I´ll give it a shot

**Comment by Black0305** [comment]
Done.

**Comment by pyure** [comment]
Fix in infitech-prototype-0.20.zip or 0.19, I forget.
